$NetBSD$

CSS grid, box alignment keywords, gradients, border radii, shadows, calc() and ::first-letter: parse, cascade and compute them.

--- src/select/autogenerated_computed.h.orig
+++ src/select/autogenerated_computed.h
@@ -19,6 +19,8 @@ struct css_computed_style_i {
  * background_position              1 + 10          8
  * background_repeat                3             
  * border_bottom_color              2               4
+ * border_bottom_left_radius        1             sizeof(ptr)
+ * border_bottom_right_radius       1             sizeof(ptr)
  * border_bottom_style              4             
  * border_bottom_width              3 + 5           4
  * border_collapse                  2             
@@ -30,9 +32,12 @@ struct css_computed_style_i {
  * border_right_width               3 + 5           4
  * border_spacing                   1 + 10          8
  * border_top_color                 2               4
+ * border_top_left_radius           1             sizeof(ptr)
+ * border_top_right_radius          1             sizeof(ptr)
  * border_top_style                 4             
  * border_top_width                 3 + 5           4
  * bottom                           2 + 5           4
+ * box_shadow                       1             sizeof(ptr)
  * box_sizing                       2             
  * break_after                      4             
  * break_before                     4             
@@ -63,8 +68,20 @@ struct css_computed_style_i {
  * font_style                       2             
  * font_variant                     2             
  * font_weight                      4             
+ * grid_auto_columns                1             sizeof(ptr)
+ * grid_auto_flow                   3             
+ * grid_auto_rows                   1             sizeof(ptr)
+ * grid_column_end                  1             sizeof(ptr)
+ * grid_column_start                1             sizeof(ptr)
+ * grid_row_end                     1             sizeof(ptr)
+ * grid_row_start                   1             sizeof(ptr)
+ * grid_template_areas              1             sizeof(ptr)
+ * grid_template_columns            1             sizeof(ptr)
+ * grid_template_rows               1             sizeof(ptr)
  * height                           2 + 5           4
  * justify_content                  3             
+ * justify_items                    4             
+ * justify_self                     4             
  * left                             2 + 5           4
  * letter_spacing                   2 + 5           4
  * line_height                      2 + 5           4
@@ -96,11 +113,13 @@ struct css_computed_style_i {
  * page_break_inside                2             
  * position                         3             
  * right                            2 + 5           4
+ * row_gap                          2 + 5           4
  * stroke_opacity                   1               4
  * table_layout                     2             
  * text_align                       4             
  * text_decoration                  5             
  * text_indent                      1 + 5           4
+ * text_shadow                      1             sizeof(ptr)
  * text_transform                   3             
  * top                              2 + 5           4
  * unicode_bidi                     2             
@@ -142,9 +161,9 @@ struct css_computed_style_i {
  * quotes                           1             sizeof(ptr)
  * 
  * ---                            ---             ---
- *                                464 bits        236 + 8sizeof(ptr) bytes
+ *                                497 bits        240 + 23sizeof(ptr) bytes
  *                                ===================
- *                                294 + 8sizeof(ptr) bytes
+ *                                303 + 23sizeof(ptr) bytes
  * 
  * Bit allocations:
  * 
@@ -157,60 +176,70 @@ struct css_computed_style_i {
  * 2  cccccccccccccccccccccccccctttttt
  * clip; text_indent
  * 
- * 3  cccccccooooooobbbbbbbppppppttttt
- * column_width; column_gap; bottom; padding_top; text_decoration
+ * 3  wwwwwwwtttttttrrrrrrriiiiiiieeee
+ * width; top; row_gap; right; text_align
  * 
- * 4  wwwwwwwtttttttrrrrrrrmmmmmmmeeee
- * width; top; right; min_width; text_align
+ * 4  mmmmmmmiiiiiiiaaaaaaaxxxxxxxoooo
+ * min_width; min_height; max_width; max_height; outline_style
  * 
- * 5  mmmmmmmaaaaaaaxxxxxxxrrrrrrroooo
- * min_height; max_width; max_height; margin_top; outline_style
+ * 5  mmmmmmmaaaaaaarrrrrrrgggggggjjjj
+ * margin_top; margin_right; margin_left; margin_bottom; justify_self
  * 
- * 6  mmmmmmmaaaaaaarrrrrrrlllllllffff
- * margin_right; margin_left; margin_bottom; line_height; font_weight
+ * 6  llllllleeeeeeefffffffhhhhhhhjjjj
+ * line_height; letter_spacing; left; height; justify_items
  * 
- * 7  llllllleeeeeeehhhhhhhfffffffcccc
- * letter_spacing; left; height; flex_basis; column_rule_style
+ * 7  fffffffcccccccooooooobbbbbbbnnnn
+ * flex_basis; column_width; column_gap; bottom; font_weight
  * 
- * 8  ppppppaaaaaaddddddlllllliiiiiwww
- * padding_right; padding_left; padding_bottom; list_style_type; display;
- * white_space
+ * 8  ppppppaaaaaaddddddiiiiiillllllzz
+ * padding_top; padding_right; padding_left; padding_bottom; list_style_type;
+ * z_index
  * 
- * 9  cccccbbbbrrrreeeeooooddddllllttt
- * cursor; break_inside; break_before; break_after; border_top_style;
- * border_right_style; border_left_style; text_transform
+ * 9  ooovvvjjjgggffflllcccbbbaaaiiiww
+ * overflow_y; overflow_x; justify_content; grid_auto_flow; font_family;
+ * flex_direction; clear; background_repeat; align_self; align_items;
+ * writing_mode
  * 
- * 10 bbbaaallliiizzwwvvuuttppoossffnn
- * background_repeat; align_self; align_items; align_content; z_index;
- * writing_mode; visibility; unicode_bidi; table_layout; page_break_inside;
- * outline_color; list_style_position; font_variant; font_style
+ * 10 bbbbbbbbbbbaaaaaaaaaaavvvvvvvvvw
+ * border_spacing; background_position; vertical_align; widows
  * 
- * 11 fflleeddccoouummnnaabbrriittppBB
- * float; flex_wrap; empty_cells; direction; content; column_span;
- * column_rule_color; column_fill; column_count; caption_side; box_sizing;
- * border_top_color; border_right_color; border_left_color; border_collapse;
- * border_bottom_color
+ * 11 tttttdddddcccccoooobbbbrrrreeeex
+ * text_decoration; display; cursor; column_rule_style; break_inside;
+ * break_before; break_after; text_shadow
  * 
- * 12 bbbbbbbbbbbaaaaaaaaaaavvvvvvvvvw
- * border_spacing; background_position; vertical_align; widows
+ * 12 bbbboooorrrrddddwwwtttpppaaagggs
+ * border_top_style; border_right_style; border_left_style;
+ * border_bottom_style; white_space; text_transform; position;
+ * page_break_before; page_break_after; stroke_opacity
  * 
- * 13 bbbbpppaaagggooovvvjjjffflllcccs
- * border_bottom_style; position; page_break_before; page_break_after;
- * overflow_y; overflow_x; justify_content; font_family; flex_direction; clear;
- * stroke_opacity
+ * 13 aaavvuuttppoollffnnFFeemmddccssq
+ * align_content; visibility; unicode_bidi; table_layout; page_break_inside;
+ * outline_color; list_style_position; font_variant; font_style; float;
+ * flex_wrap; empty_cells; direction; content; column_span; quotes
+ * 
+ * 14 ccoollaabbrrddeeppttkkgghOismuGw
+ * column_rule_color; column_fill; column_count; caption_side; box_sizing;
+ * border_top_color; border_right_color; border_left_color; border_collapse;
+ * border_bottom_color; background_color; background_attachment; orphans;
+ * order; opacity; list_style_image; grid_template_rows; grid_template_columns;
+ * grid_template_areas; grid_row_start
  * 
- * 14 bbaaqorplfeicuCk................
- * background_color; background_attachment; quotes; orphans; order; opacity;
- * list_style_image; flex_shrink; flex_grow; fill_opacity; counter_reset;
- * counter_increment; color; background_image
+ * 15 gridaflocuCbetmsk...............
+ * grid_row_end; grid_column_start; grid_column_end; grid_auto_rows;
+ * grid_auto_columns; flex_shrink; flex_grow; fill_opacity; counter_reset;
+ * counter_increment; color; box_shadow; border_top_right_radius;
+ * border_top_left_radius; border_bottom_right_radius;
+ * border_bottom_left_radius; background_image
  */
-	uint32_t bits[15];
+	uint32_t bits[16];
 	
 	css_color background_color;
 	lwc_string *background_image;
 	css_fixed background_position_a;
 	css_fixed background_position_b;
 	css_color border_bottom_color;
+	lwc_string *border_bottom_left_radius;
+	lwc_string *border_bottom_right_radius;
 	css_fixed border_bottom_width;
 	css_color border_left_color;
 	css_fixed border_left_width;
@@ -219,8 +248,11 @@ struct css_computed_style_i {
 	css_fixed border_spacing_a;
 	css_fixed border_spacing_b;
 	css_color border_top_color;
+	lwc_string *border_top_left_radius;
+	lwc_string *border_top_right_radius;
 	css_fixed border_top_width;
 	css_fixed bottom;
+	lwc_string *box_shadow;
 	css_fixed clip_a;
 	css_fixed clip_b;
 	css_fixed clip_c;
@@ -236,6 +268,15 @@ struct css_computed_style_i {
 	css_fixed flex_grow;
 	css_fixed flex_shrink;
 	css_fixed font_size;
+	lwc_string *grid_auto_columns;
+	lwc_string *grid_auto_rows;
+	lwc_string *grid_column_end;
+	lwc_string *grid_column_start;
+	lwc_string *grid_row_end;
+	lwc_string *grid_row_start;
+	lwc_string *grid_template_areas;
+	lwc_string *grid_template_columns;
+	lwc_string *grid_template_rows;
 	css_fixed height;
 	css_fixed left;
 	css_fixed letter_spacing;
@@ -259,8 +300,10 @@ struct css_computed_style_i {
 	css_fixed padding_right;
 	css_fixed padding_top;
 	css_fixed right;
+	css_fixed row_gap;
 	css_fixed stroke_opacity;
 	css_fixed text_indent;
+	lwc_string *text_shadow;
 	css_fixed top;
 	css_fixed vertical_align;
 	int32_t widows;
