$NetBSD$

CSS grid properties, and the box alignment keywords: parse, cascade and compute them.

--- src/select/autogenerated_computed.h.orig
+++ src/select/autogenerated_computed.h
@@ -63,8 +63,20 @@ struct css_computed_style_i {
  * font_style                       2             
  * font_variant                     2             
  * font_weight                      4             
+ * grid_auto_columns                1             sizeof(ptr)
+ * grid_auto_flow                   3             
+ * grid_auto_rows                   1             sizeof(ptr)
+ * grid_column_end                  1             sizeof(ptr)
+ * grid_column_start                1             sizeof(ptr)
+ * grid_row_end                     1             sizeof(ptr)
+ * grid_row_start                   1             sizeof(ptr)
+ * grid_template_areas              1             sizeof(ptr)
+ * grid_template_columns            1             sizeof(ptr)
+ * grid_template_rows               1             sizeof(ptr)
  * height                           2 + 5           4
  * justify_content                  3             
+ * justify_items                    4             
+ * justify_self                     4             
  * left                             2 + 5           4
  * letter_spacing                   2 + 5           4
  * line_height                      2 + 5           4
@@ -96,6 +108,7 @@ struct css_computed_style_i {
  * page_break_inside                2             
  * position                         3             
  * right                            2 + 5           4
+ * row_gap                          2 + 5           4
  * stroke_opacity                   1               4
  * table_layout                     2             
  * text_align                       4             
@@ -142,9 +155,9 @@ struct css_computed_style_i {
  * quotes                           1             sizeof(ptr)
  * 
  * ---                            ---             ---
- *                                464 bits        236 + 8sizeof(ptr) bytes
+ *                                491 bits        240 + 17sizeof(ptr) bytes
  *                                ===================
- *                                294 + 8sizeof(ptr) bytes
+ *                                302 + 17sizeof(ptr) bytes
  * 
  * Bit allocations:
  * 
@@ -157,54 +170,60 @@ struct css_computed_style_i {
  * 2  cccccccccccccccccccccccccctttttt
  * clip; text_indent
  * 
- * 3  cccccccooooooobbbbbbbppppppttttt
- * column_width; column_gap; bottom; padding_top; text_decoration
+ * 3  wwwwwwwtttttttrrrrrrriiiiiiieeee
+ * width; top; row_gap; right; text_align
  * 
- * 4  wwwwwwwtttttttrrrrrrrmmmmmmmeeee
- * width; top; right; min_width; text_align
+ * 4  mmmmmmmiiiiiiiaaaaaaaxxxxxxxoooo
+ * min_width; min_height; max_width; max_height; outline_style
  * 
- * 5  mmmmmmmaaaaaaaxxxxxxxrrrrrrroooo
- * min_height; max_width; max_height; margin_top; outline_style
+ * 5  mmmmmmmaaaaaaarrrrrrrgggggggjjjj
+ * margin_top; margin_right; margin_left; margin_bottom; justify_self
  * 
- * 6  mmmmmmmaaaaaaarrrrrrrlllllllffff
- * margin_right; margin_left; margin_bottom; line_height; font_weight
+ * 6  llllllleeeeeeefffffffhhhhhhhjjjj
+ * line_height; letter_spacing; left; height; justify_items
  * 
- * 7  llllllleeeeeeehhhhhhhfffffffcccc
- * letter_spacing; left; height; flex_basis; column_rule_style
+ * 7  fffffffcccccccooooooobbbbbbbnnnn
+ * flex_basis; column_width; column_gap; bottom; font_weight
  * 
- * 8  ppppppaaaaaaddddddlllllliiiiiwww
- * padding_right; padding_left; padding_bottom; list_style_type; display;
- * white_space
+ * 8  ppppppaaaaaaddddddiiiiiillllllzz
+ * padding_top; padding_right; padding_left; padding_bottom; list_style_type;
+ * z_index
  * 
- * 9  cccccbbbbrrrreeeeooooddddllllttt
- * cursor; break_inside; break_before; break_after; border_top_style;
- * border_right_style; border_left_style; text_transform
+ * 9  ooovvvjjjgggffflllcccbbbaaaiiiww
+ * overflow_y; overflow_x; justify_content; grid_auto_flow; font_family;
+ * flex_direction; clear; background_repeat; align_self; align_items;
+ * writing_mode
  * 
- * 10 bbbaaallliiizzwwvvuuttppoossffnn
- * background_repeat; align_self; align_items; align_content; z_index;
- * writing_mode; visibility; unicode_bidi; table_layout; page_break_inside;
- * outline_color; list_style_position; font_variant; font_style
+ * 10 bbbbbbbbbbbaaaaaaaaaaavvvvvvvvvw
+ * border_spacing; background_position; vertical_align; widows
  * 
- * 11 fflleeddccoouummnnaabbrriittppBB
- * float; flex_wrap; empty_cells; direction; content; column_span;
- * column_rule_color; column_fill; column_count; caption_side; box_sizing;
- * border_top_color; border_right_color; border_left_color; border_collapse;
- * border_bottom_color
+ * 11 tttttdddddcccccoooobbbbrrrreeees
+ * text_decoration; display; cursor; column_rule_style; break_inside;
+ * break_before; break_after; stroke_opacity
  * 
- * 12 bbbbbbbbbbbaaaaaaaaaaavvvvvvvvvw
- * border_spacing; background_position; vertical_align; widows
+ * 12 bbbboooorrrrddddwwwtttpppaaagggq
+ * border_top_style; border_right_style; border_left_style;
+ * border_bottom_style; white_space; text_transform; position;
+ * page_break_before; page_break_after; quotes
  * 
- * 13 bbbbpppaaagggooovvvjjjffflllcccs
- * border_bottom_style; position; page_break_before; page_break_after;
- * overflow_y; overflow_x; justify_content; font_family; flex_direction; clear;
- * stroke_opacity
+ * 13 aaavvuuttppoollffnnFFeemmddccssr
+ * align_content; visibility; unicode_bidi; table_layout; page_break_inside;
+ * outline_color; list_style_position; font_variant; font_style; float;
+ * flex_wrap; empty_cells; direction; content; column_span; orphans
+ * 
+ * 14 ccoollaabbrrddeeppttkkggOismuGwn
+ * column_rule_color; column_fill; column_count; caption_side; box_sizing;
+ * border_top_color; border_right_color; border_left_color; border_collapse;
+ * border_bottom_color; background_color; background_attachment; order;
+ * opacity; list_style_image; grid_template_rows; grid_template_columns;
+ * grid_template_areas; grid_row_start; grid_row_end
  * 
- * 14 bbaaqorplfeicuCk................
- * background_color; background_attachment; quotes; orphans; order; opacity;
- * list_style_image; flex_shrink; flex_grow; fill_opacity; counter_reset;
- * counter_increment; color; background_image
+ * 15 gridflocuCb.....................
+ * grid_column_start; grid_column_end; grid_auto_rows; grid_auto_columns;
+ * flex_shrink; flex_grow; fill_opacity; counter_reset; counter_increment;
+ * color; background_image
  */
-	uint32_t bits[15];
+	uint32_t bits[16];
 	
 	css_color background_color;
 	lwc_string *background_image;
@@ -236,6 +255,15 @@ struct css_computed_style_i {
 	css_fixed flex_grow;
 	css_fixed flex_shrink;
 	css_fixed font_size;
+	lwc_string *grid_auto_columns;
+	lwc_string *grid_auto_rows;
+	lwc_string *grid_column_end;
+	lwc_string *grid_column_start;
+	lwc_string *grid_row_end;
+	lwc_string *grid_row_start;
+	lwc_string *grid_template_areas;
+	lwc_string *grid_template_columns;
+	lwc_string *grid_template_rows;
 	css_fixed height;
 	css_fixed left;
 	css_fixed letter_spacing;
@@ -259,6 +287,7 @@ struct css_computed_style_i {
 	css_fixed padding_right;
 	css_fixed padding_top;
 	css_fixed right;
+	css_fixed row_gap;
 	css_fixed stroke_opacity;
 	css_fixed text_indent;
 	css_fixed top;
