$NetBSD$

CSS grid, box alignment keywords, gradients, border radii and shadows: parse, cascade and compute them.

--- src/parse/propstrings.h.orig
+++ src/parse/propstrings.h
@@ -68,8 +68,10 @@ enum {
 	TEXT_DECORATION, TEXT_INDENT, TEXT_TRANSFORM, TOP, UNICODE_BIDI,
 	VERTICAL_ALIGN, VISIBILITY, VOICE_FAMILY, VOLUME, WHITE_SPACE, WIDOWS,
 	WIDTH, WORD_SPACING, WRITING_MODE, Z_INDEX,
+	/* grid, and the gaps and justify-items/-self it brings */
+	GAP, GRID_AREA, GRID_AUTO_COLUMNS, GRID_AUTO_FLOW, GRID_AUTO_ROWS, GRID_COLUMN, GRID_COLUMN_END, GRID_COLUMN_GAP, GRID_COLUMN_START, GRID_GAP, GRID_ROW, GRID_ROW_END, GRID_ROW_GAP, GRID_ROW_START, GRID_TEMPLATE, GRID_TEMPLATE_AREAS, GRID_TEMPLATE_COLUMNS, GRID_TEMPLATE_ROWS, JUSTIFY_ITEMS, JUSTIFY_SELF, ROW_GAP, BORDER_RADIUS, BORDER_BOTTOM_LEFT_RADIUS, BORDER_BOTTOM_RIGHT_RADIUS, BORDER_TOP_LEFT_RADIUS, BORDER_TOP_RIGHT_RADIUS, BOX_SHADOW, TEXT_SHADOW,
 
-	LAST_PROP = Z_INDEX,
+	LAST_PROP = TEXT_SHADOW,
 
 	/* Other keywords */
 	INHERIT, UNSET, IMPORTANT, NONE, BOTH, FIXED, SCROLL, TRANSPARENT,
@@ -110,7 +112,8 @@ enum {
 	VERTICAL_LR, CONTENT_BOX, BORDER_BOX, STRETCH, INLINE_FLEX, FLEX_START,
 	FLEX_END, SPACE_BETWEEN, SPACE_AROUND, SPACE_EVENLY, ROW, ROW_REVERSE,
 	COLUMN_REVERSE, WRAP_STRING, WRAP_REVERSE, AND, OR, ONLY, INFINITE,
-	GRID, INLINE_GRID, STICKY,
+	GRID, INLINE_GRID, STICKY, DENSE, SPAN, KW_START, KW_END,
+	SELF_START, SELF_END,
 
 	/* Named colours */
 	FIRST_COLOUR,
