$NetBSD$

CSS grid properties, and the box alignment keywords: parse, cascade and compute them.

--- src/select/autogenerated_propset.h.orig
+++ src/select/autogenerated_propset.h
@@ -8,9 +8,9 @@
 /** Default values are 'initial value', unless the property is inherited,
  *  in which case it is 'inherit'. */
 
-#define ALIGN_CONTENT_INDEX 10
-#define ALIGN_CONTENT_SHIFT 20
-#define ALIGN_CONTENT_MASK 0x700000
+#define ALIGN_CONTENT_INDEX 13
+#define ALIGN_CONTENT_SHIFT 29
+#define ALIGN_CONTENT_MASK 0xe0000000
 
 static inline css_error set_align_content(css_computed_style *style, uint8_t
 		type)
@@ -27,9 +27,9 @@ static inline css_error set_align_content(css_computed_style *style, uint8_t
 #undef ALIGN_CONTENT_SHIFT
 #undef ALIGN_CONTENT_MASK
 
-#define ALIGN_ITEMS_INDEX 10
-#define ALIGN_ITEMS_SHIFT 23
-#define ALIGN_ITEMS_MASK 0x3800000
+#define ALIGN_ITEMS_INDEX 9
+#define ALIGN_ITEMS_SHIFT 2
+#define ALIGN_ITEMS_MASK 0x1c
 
 static inline css_error set_align_items(css_computed_style *style, uint8_t type)
 {
@@ -45,9 +45,9 @@ static inline css_error set_align_items(css_computed_style *style, uint8_t type)
 #undef ALIGN_ITEMS_SHIFT
 #undef ALIGN_ITEMS_MASK
 
-#define ALIGN_SELF_INDEX 10
-#define ALIGN_SELF_SHIFT 26
-#define ALIGN_SELF_MASK 0x1c000000
+#define ALIGN_SELF_INDEX 9
+#define ALIGN_SELF_SHIFT 5
+#define ALIGN_SELF_MASK 0xe0
 
 static inline css_error set_align_self(css_computed_style *style, uint8_t type)
 {
@@ -64,8 +64,8 @@ static inline css_error set_align_self(css_computed_style *style, uint8_t type)
 #undef ALIGN_SELF_MASK
 
 #define BACKGROUND_ATTACHMENT_INDEX 14
-#define BACKGROUND_ATTACHMENT_SHIFT 28
-#define BACKGROUND_ATTACHMENT_MASK 0x30000000
+#define BACKGROUND_ATTACHMENT_SHIFT 8
+#define BACKGROUND_ATTACHMENT_MASK 0x300
 
 static inline css_error set_background_attachment(css_computed_style *style,
 		uint8_t type)
@@ -83,8 +83,8 @@ static inline css_error set_background_attachment(css_computed_style *style,
 #undef BACKGROUND_ATTACHMENT_MASK
 
 #define BACKGROUND_COLOR_INDEX 14
-#define BACKGROUND_COLOR_SHIFT 30
-#define BACKGROUND_COLOR_MASK 0xc0000000
+#define BACKGROUND_COLOR_SHIFT 10
+#define BACKGROUND_COLOR_MASK 0xc00
 
 static inline css_error set_background_color(css_computed_style *style, uint8_t
 		type, css_color color)
@@ -103,9 +103,9 @@ static inline css_error set_background_color(css_computed_style *style, uint8_t
 #undef BACKGROUND_COLOR_SHIFT
 #undef BACKGROUND_COLOR_MASK
 
-#define BACKGROUND_IMAGE_INDEX 14
-#define BACKGROUND_IMAGE_SHIFT 16
-#define BACKGROUND_IMAGE_MASK 0x10000
+#define BACKGROUND_IMAGE_INDEX 15
+#define BACKGROUND_IMAGE_SHIFT 21
+#define BACKGROUND_IMAGE_MASK 0x200000
 
 static inline css_error set_background_image(css_computed_style *style, uint8_t
 		type, lwc_string *string)
@@ -133,7 +133,7 @@ static inline css_error set_background_image(css_computed_style *style, uint8_t
 #undef BACKGROUND_IMAGE_SHIFT
 #undef BACKGROUND_IMAGE_MASK
 
-#define BACKGROUND_POSITION_INDEX 12
+#define BACKGROUND_POSITION_INDEX 10
 #define BACKGROUND_POSITION_SHIFT 10
 #define BACKGROUND_POSITION_MASK 0x1ffc00
 
@@ -158,9 +158,9 @@ static inline css_error set_background_position(css_computed_style *style,
 #undef BACKGROUND_POSITION_SHIFT
 #undef BACKGROUND_POSITION_MASK
 
-#define BACKGROUND_REPEAT_INDEX 10
-#define BACKGROUND_REPEAT_SHIFT 29
-#define BACKGROUND_REPEAT_MASK 0xe0000000
+#define BACKGROUND_REPEAT_INDEX 9
+#define BACKGROUND_REPEAT_SHIFT 8
+#define BACKGROUND_REPEAT_MASK 0x700
 
 static inline css_error set_background_repeat(css_computed_style *style,
 		uint8_t type)
@@ -177,9 +177,9 @@ static inline css_error set_background_repeat(css_computed_style *style,
 #undef BACKGROUND_REPEAT_SHIFT
 #undef BACKGROUND_REPEAT_MASK
 
-#define BORDER_BOTTOM_COLOR_INDEX 11
-#define BORDER_BOTTOM_COLOR_SHIFT 0
-#define BORDER_BOTTOM_COLOR_MASK 0x3
+#define BORDER_BOTTOM_COLOR_INDEX 14
+#define BORDER_BOTTOM_COLOR_SHIFT 12
+#define BORDER_BOTTOM_COLOR_MASK 0x3000
 
 static inline css_error set_border_bottom_color(css_computed_style *style,
 		uint8_t type, css_color color)
@@ -198,9 +198,9 @@ static inline css_error set_border_bottom_color(css_computed_style *style,
 #undef BORDER_BOTTOM_COLOR_SHIFT
 #undef BORDER_BOTTOM_COLOR_MASK
 
-#define BORDER_BOTTOM_STYLE_INDEX 13
-#define BORDER_BOTTOM_STYLE_SHIFT 28
-#define BORDER_BOTTOM_STYLE_MASK 0xf0000000
+#define BORDER_BOTTOM_STYLE_INDEX 12
+#define BORDER_BOTTOM_STYLE_SHIFT 16
+#define BORDER_BOTTOM_STYLE_MASK 0xf0000
 
 static inline css_error set_border_bottom_style(css_computed_style *style,
 		uint8_t type)
@@ -238,9 +238,9 @@ static inline css_error set_border_bottom_width(css_computed_style *style,
 #undef BORDER_BOTTOM_WIDTH_SHIFT
 #undef BORDER_BOTTOM_WIDTH_MASK
 
-#define BORDER_COLLAPSE_INDEX 11
-#define BORDER_COLLAPSE_SHIFT 2
-#define BORDER_COLLAPSE_MASK 0xc
+#define BORDER_COLLAPSE_INDEX 14
+#define BORDER_COLLAPSE_SHIFT 14
+#define BORDER_COLLAPSE_MASK 0xc000
 
 static inline css_error set_border_collapse(css_computed_style *style, uint8_t
 		type)
@@ -257,9 +257,9 @@ static inline css_error set_border_collapse(css_computed_style *style, uint8_t
 #undef BORDER_COLLAPSE_SHIFT
 #undef BORDER_COLLAPSE_MASK
 
-#define BORDER_LEFT_COLOR_INDEX 11
-#define BORDER_LEFT_COLOR_SHIFT 4
-#define BORDER_LEFT_COLOR_MASK 0x30
+#define BORDER_LEFT_COLOR_INDEX 14
+#define BORDER_LEFT_COLOR_SHIFT 16
+#define BORDER_LEFT_COLOR_MASK 0x30000
 
 static inline css_error set_border_left_color(css_computed_style *style,
 		uint8_t type, css_color color)
@@ -278,9 +278,9 @@ static inline css_error set_border_left_color(css_computed_style *style,
 #undef BORDER_LEFT_COLOR_SHIFT
 #undef BORDER_LEFT_COLOR_MASK
 
-#define BORDER_LEFT_STYLE_INDEX 9
-#define BORDER_LEFT_STYLE_SHIFT 3
-#define BORDER_LEFT_STYLE_MASK 0x78
+#define BORDER_LEFT_STYLE_INDEX 12
+#define BORDER_LEFT_STYLE_SHIFT 20
+#define BORDER_LEFT_STYLE_MASK 0xf00000
 
 static inline css_error set_border_left_style(css_computed_style *style,
 		uint8_t type)
@@ -318,9 +318,9 @@ static inline css_error set_border_left_width(css_computed_style *style,
 #undef BORDER_LEFT_WIDTH_SHIFT
 #undef BORDER_LEFT_WIDTH_MASK
 
-#define BORDER_RIGHT_COLOR_INDEX 11
-#define BORDER_RIGHT_COLOR_SHIFT 6
-#define BORDER_RIGHT_COLOR_MASK 0xc0
+#define BORDER_RIGHT_COLOR_INDEX 14
+#define BORDER_RIGHT_COLOR_SHIFT 18
+#define BORDER_RIGHT_COLOR_MASK 0xc0000
 
 static inline css_error set_border_right_color(css_computed_style *style,
 		uint8_t type, css_color color)
@@ -339,9 +339,9 @@ static inline css_error set_border_right_color(css_computed_style *style,
 #undef BORDER_RIGHT_COLOR_SHIFT
 #undef BORDER_RIGHT_COLOR_MASK
 
-#define BORDER_RIGHT_STYLE_INDEX 9
-#define BORDER_RIGHT_STYLE_SHIFT 7
-#define BORDER_RIGHT_STYLE_MASK 0x780
+#define BORDER_RIGHT_STYLE_INDEX 12
+#define BORDER_RIGHT_STYLE_SHIFT 24
+#define BORDER_RIGHT_STYLE_MASK 0xf000000
 
 static inline css_error set_border_right_style(css_computed_style *style,
 		uint8_t type)
@@ -379,7 +379,7 @@ static inline css_error set_border_right_width(css_computed_style *style,
 #undef BORDER_RIGHT_WIDTH_SHIFT
 #undef BORDER_RIGHT_WIDTH_MASK
 
-#define BORDER_SPACING_INDEX 12
+#define BORDER_SPACING_INDEX 10
 #define BORDER_SPACING_SHIFT 21
 #define BORDER_SPACING_MASK 0xffe00000
 
@@ -403,9 +403,9 @@ static inline css_error set_border_spacing(css_computed_style *style, uint8_t
 #undef BORDER_SPACING_SHIFT
 #undef BORDER_SPACING_MASK
 
-#define BORDER_TOP_COLOR_INDEX 11
-#define BORDER_TOP_COLOR_SHIFT 8
-#define BORDER_TOP_COLOR_MASK 0x300
+#define BORDER_TOP_COLOR_INDEX 14
+#define BORDER_TOP_COLOR_SHIFT 20
+#define BORDER_TOP_COLOR_MASK 0x300000
 
 static inline css_error set_border_top_color(css_computed_style *style, uint8_t
 		type, css_color color)
@@ -424,9 +424,9 @@ static inline css_error set_border_top_color(css_computed_style *style, uint8_t
 #undef BORDER_TOP_COLOR_SHIFT
 #undef BORDER_TOP_COLOR_MASK
 
-#define BORDER_TOP_STYLE_INDEX 9
-#define BORDER_TOP_STYLE_SHIFT 11
-#define BORDER_TOP_STYLE_MASK 0x7800
+#define BORDER_TOP_STYLE_INDEX 12
+#define BORDER_TOP_STYLE_SHIFT 28
+#define BORDER_TOP_STYLE_MASK 0xf0000000
 
 static inline css_error set_border_top_style(css_computed_style *style, uint8_t
 		type)
@@ -464,9 +464,9 @@ static inline css_error set_border_top_width(css_computed_style *style, uint8_t
 #undef BORDER_TOP_WIDTH_SHIFT
 #undef BORDER_TOP_WIDTH_MASK
 
-#define BOTTOM_INDEX 3
-#define BOTTOM_SHIFT 11
-#define BOTTOM_MASK 0x3f800
+#define BOTTOM_INDEX 7
+#define BOTTOM_SHIFT 4
+#define BOTTOM_MASK 0x7f0
 
 static inline css_error set_bottom(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -485,9 +485,9 @@ static inline css_error set_bottom(css_computed_style *style, uint8_t type,
 #undef BOTTOM_SHIFT
 #undef BOTTOM_MASK
 
-#define BOX_SIZING_INDEX 11
-#define BOX_SIZING_SHIFT 10
-#define BOX_SIZING_MASK 0xc00
+#define BOX_SIZING_INDEX 14
+#define BOX_SIZING_SHIFT 22
+#define BOX_SIZING_MASK 0xc00000
 
 static inline css_error set_box_sizing(css_computed_style *style, uint8_t type)
 {
@@ -503,9 +503,9 @@ static inline css_error set_box_sizing(css_computed_style *style, uint8_t type)
 #undef BOX_SIZING_SHIFT
 #undef BOX_SIZING_MASK
 
-#define BREAK_AFTER_INDEX 9
-#define BREAK_AFTER_SHIFT 15
-#define BREAK_AFTER_MASK 0x78000
+#define BREAK_AFTER_INDEX 11
+#define BREAK_AFTER_SHIFT 1
+#define BREAK_AFTER_MASK 0x1e
 
 static inline css_error set_break_after(css_computed_style *style, uint8_t type)
 {
@@ -521,9 +521,9 @@ static inline css_error set_break_after(css_computed_style *style, uint8_t type)
 #undef BREAK_AFTER_SHIFT
 #undef BREAK_AFTER_MASK
 
-#define BREAK_BEFORE_INDEX 9
-#define BREAK_BEFORE_SHIFT 19
-#define BREAK_BEFORE_MASK 0x780000
+#define BREAK_BEFORE_INDEX 11
+#define BREAK_BEFORE_SHIFT 5
+#define BREAK_BEFORE_MASK 0x1e0
 
 static inline css_error set_break_before(css_computed_style *style, uint8_t
 		type)
@@ -540,9 +540,9 @@ static inline css_error set_break_before(css_computed_style *style, uint8_t
 #undef BREAK_BEFORE_SHIFT
 #undef BREAK_BEFORE_MASK
 
-#define BREAK_INSIDE_INDEX 9
-#define BREAK_INSIDE_SHIFT 23
-#define BREAK_INSIDE_MASK 0x7800000
+#define BREAK_INSIDE_INDEX 11
+#define BREAK_INSIDE_SHIFT 9
+#define BREAK_INSIDE_MASK 0x1e00
 
 static inline css_error set_break_inside(css_computed_style *style, uint8_t
 		type)
@@ -559,9 +559,9 @@ static inline css_error set_break_inside(css_computed_style *style, uint8_t
 #undef BREAK_INSIDE_SHIFT
 #undef BREAK_INSIDE_MASK
 
-#define CAPTION_SIDE_INDEX 11
-#define CAPTION_SIDE_SHIFT 12
-#define CAPTION_SIDE_MASK 0x3000
+#define CAPTION_SIDE_INDEX 14
+#define CAPTION_SIDE_SHIFT 24
+#define CAPTION_SIDE_MASK 0x3000000
 
 static inline css_error set_caption_side(css_computed_style *style, uint8_t
 		type)
@@ -578,9 +578,9 @@ static inline css_error set_caption_side(css_computed_style *style, uint8_t
 #undef CAPTION_SIDE_SHIFT
 #undef CAPTION_SIDE_MASK
 
-#define CLEAR_INDEX 13
-#define CLEAR_SHIFT 1
-#define CLEAR_MASK 0xe
+#define CLEAR_INDEX 9
+#define CLEAR_SHIFT 11
+#define CLEAR_MASK 0x3800
 
 static inline css_error set_clear(css_computed_style *style, uint8_t type)
 {
@@ -638,9 +638,9 @@ static inline css_error set_clip(
 #undef CLIP_SHIFT
 #undef CLIP_MASK
 
-#define COLOR_INDEX 14
-#define COLOR_SHIFT 17
-#define COLOR_MASK 0x20000
+#define COLOR_INDEX 15
+#define COLOR_SHIFT 22
+#define COLOR_MASK 0x400000
 
 static inline css_error set_color(css_computed_style *style, uint8_t type,
 		css_color color)
@@ -658,9 +658,9 @@ static inline css_error set_color(css_computed_style *style, uint8_t type,
 #undef COLOR_SHIFT
 #undef COLOR_MASK
 
-#define COLUMN_COUNT_INDEX 11
-#define COLUMN_COUNT_SHIFT 14
-#define COLUMN_COUNT_MASK 0xc000
+#define COLUMN_COUNT_INDEX 14
+#define COLUMN_COUNT_SHIFT 26
+#define COLUMN_COUNT_MASK 0xc000000
 
 static inline css_error set_column_count(css_computed_style *style, uint8_t
 		type, int32_t integer)
@@ -679,9 +679,9 @@ static inline css_error set_column_count(css_computed_style *style, uint8_t
 #undef COLUMN_COUNT_SHIFT
 #undef COLUMN_COUNT_MASK
 
-#define COLUMN_FILL_INDEX 11
-#define COLUMN_FILL_SHIFT 16
-#define COLUMN_FILL_MASK 0x30000
+#define COLUMN_FILL_INDEX 14
+#define COLUMN_FILL_SHIFT 28
+#define COLUMN_FILL_MASK 0x30000000
 
 static inline css_error set_column_fill(css_computed_style *style, uint8_t type)
 {
@@ -697,9 +697,9 @@ static inline css_error set_column_fill(css_computed_style *style, uint8_t type)
 #undef COLUMN_FILL_SHIFT
 #undef COLUMN_FILL_MASK
 
-#define COLUMN_GAP_INDEX 3
-#define COLUMN_GAP_SHIFT 18
-#define COLUMN_GAP_MASK 0x1fc0000
+#define COLUMN_GAP_INDEX 7
+#define COLUMN_GAP_SHIFT 11
+#define COLUMN_GAP_MASK 0x3f800
 
 static inline css_error set_column_gap(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -718,9 +718,9 @@ static inline css_error set_column_gap(css_computed_style *style, uint8_t type,
 #undef COLUMN_GAP_SHIFT
 #undef COLUMN_GAP_MASK
 
-#define COLUMN_RULE_COLOR_INDEX 11
-#define COLUMN_RULE_COLOR_SHIFT 18
-#define COLUMN_RULE_COLOR_MASK 0xc0000
+#define COLUMN_RULE_COLOR_INDEX 14
+#define COLUMN_RULE_COLOR_SHIFT 30
+#define COLUMN_RULE_COLOR_MASK 0xc0000000
 
 static inline css_error set_column_rule_color(css_computed_style *style,
 		uint8_t type, css_color color)
@@ -739,9 +739,9 @@ static inline css_error set_column_rule_color(css_computed_style *style,
 #undef COLUMN_RULE_COLOR_SHIFT
 #undef COLUMN_RULE_COLOR_MASK
 
-#define COLUMN_RULE_STYLE_INDEX 7
-#define COLUMN_RULE_STYLE_SHIFT 0
-#define COLUMN_RULE_STYLE_MASK 0xf
+#define COLUMN_RULE_STYLE_INDEX 11
+#define COLUMN_RULE_STYLE_SHIFT 13
+#define COLUMN_RULE_STYLE_MASK 0x1e000
 
 static inline css_error set_column_rule_style(css_computed_style *style,
 		uint8_t type)
@@ -779,9 +779,9 @@ static inline css_error set_column_rule_width(css_computed_style *style,
 #undef COLUMN_RULE_WIDTH_SHIFT
 #undef COLUMN_RULE_WIDTH_MASK
 
-#define COLUMN_SPAN_INDEX 11
-#define COLUMN_SPAN_SHIFT 20
-#define COLUMN_SPAN_MASK 0x300000
+#define COLUMN_SPAN_INDEX 13
+#define COLUMN_SPAN_SHIFT 1
+#define COLUMN_SPAN_MASK 0x6
 
 static inline css_error set_column_span(css_computed_style *style, uint8_t type)
 {
@@ -797,9 +797,9 @@ static inline css_error set_column_span(css_computed_style *style, uint8_t type)
 #undef COLUMN_SPAN_SHIFT
 #undef COLUMN_SPAN_MASK
 
-#define COLUMN_WIDTH_INDEX 3
-#define COLUMN_WIDTH_SHIFT 25
-#define COLUMN_WIDTH_MASK 0xfe000000
+#define COLUMN_WIDTH_INDEX 7
+#define COLUMN_WIDTH_SHIFT 18
+#define COLUMN_WIDTH_MASK 0x1fc0000
 
 static inline css_error set_column_width(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -818,9 +818,9 @@ static inline css_error set_column_width(css_computed_style *style, uint8_t
 #undef COLUMN_WIDTH_SHIFT
 #undef COLUMN_WIDTH_MASK
 
-#define CONTENT_INDEX 11
-#define CONTENT_SHIFT 22
-#define CONTENT_MASK 0xc00000
+#define CONTENT_INDEX 13
+#define CONTENT_SHIFT 3
+#define CONTENT_MASK 0x18
 static inline css_error set_content(
 		css_computed_style *style, uint8_t type,
 		css_computed_content_item *content)
@@ -901,9 +901,9 @@ static inline css_error set_content(
 #undef CONTENT_SHIFT
 #undef CONTENT_MASK
 
-#define COUNTER_INCREMENT_INDEX 14
-#define COUNTER_INCREMENT_SHIFT 18
-#define COUNTER_INCREMENT_MASK 0x40000
+#define COUNTER_INCREMENT_INDEX 15
+#define COUNTER_INCREMENT_SHIFT 23
+#define COUNTER_INCREMENT_MASK 0x800000
 
 static inline css_error set_counter_increment(css_computed_style *style,
 		uint8_t type, css_computed_counter *counter_arr)
@@ -937,9 +937,9 @@ static inline css_error set_counter_increment(css_computed_style *style,
 #undef COUNTER_INCREMENT_SHIFT
 #undef COUNTER_INCREMENT_MASK
 
-#define COUNTER_RESET_INDEX 14
-#define COUNTER_RESET_SHIFT 19
-#define COUNTER_RESET_MASK 0x80000
+#define COUNTER_RESET_INDEX 15
+#define COUNTER_RESET_SHIFT 24
+#define COUNTER_RESET_MASK 0x1000000
 
 static inline css_error set_counter_reset(css_computed_style *style, uint8_t
 		type, css_computed_counter *counter_arr)
@@ -973,9 +973,9 @@ static inline css_error set_counter_reset(css_computed_style *style, uint8_t
 #undef COUNTER_RESET_SHIFT
 #undef COUNTER_RESET_MASK
 
-#define CURSOR_INDEX 9
-#define CURSOR_SHIFT 27
-#define CURSOR_MASK 0xf8000000
+#define CURSOR_INDEX 11
+#define CURSOR_SHIFT 17
+#define CURSOR_MASK 0x3e0000
 
 static inline css_error set_cursor(css_computed_style *style, uint8_t type,
 		lwc_string **string_arr)
@@ -1009,9 +1009,9 @@ static inline css_error set_cursor(css_computed_style *style, uint8_t type,
 #undef CURSOR_SHIFT
 #undef CURSOR_MASK
 
-#define DIRECTION_INDEX 11
-#define DIRECTION_SHIFT 24
-#define DIRECTION_MASK 0x3000000
+#define DIRECTION_INDEX 13
+#define DIRECTION_SHIFT 5
+#define DIRECTION_MASK 0x60
 
 static inline css_error set_direction(css_computed_style *style, uint8_t type)
 {
@@ -1027,9 +1027,9 @@ static inline css_error set_direction(css_computed_style *style, uint8_t type)
 #undef DIRECTION_SHIFT
 #undef DIRECTION_MASK
 
-#define DISPLAY_INDEX 8
-#define DISPLAY_SHIFT 3
-#define DISPLAY_MASK 0xf8
+#define DISPLAY_INDEX 11
+#define DISPLAY_SHIFT 22
+#define DISPLAY_MASK 0x7c00000
 
 static inline css_error set_display(css_computed_style *style, uint8_t type)
 {
@@ -1045,9 +1045,9 @@ static inline css_error set_display(css_computed_style *style, uint8_t type)
 #undef DISPLAY_SHIFT
 #undef DISPLAY_MASK
 
-#define EMPTY_CELLS_INDEX 11
-#define EMPTY_CELLS_SHIFT 26
-#define EMPTY_CELLS_MASK 0xc000000
+#define EMPTY_CELLS_INDEX 13
+#define EMPTY_CELLS_SHIFT 7
+#define EMPTY_CELLS_MASK 0x180
 
 static inline css_error set_empty_cells(css_computed_style *style, uint8_t type)
 {
@@ -1063,9 +1063,9 @@ static inline css_error set_empty_cells(css_computed_style *style, uint8_t type)
 #undef EMPTY_CELLS_SHIFT
 #undef EMPTY_CELLS_MASK
 
-#define FILL_OPACITY_INDEX 14
-#define FILL_OPACITY_SHIFT 20
-#define FILL_OPACITY_MASK 0x100000
+#define FILL_OPACITY_INDEX 15
+#define FILL_OPACITY_SHIFT 25
+#define FILL_OPACITY_MASK 0x2000000
 
 static inline css_error set_fill_opacity(css_computed_style *style, uint8_t
 		type, css_fixed fixed)
@@ -1085,8 +1085,8 @@ static inline css_error set_fill_opacity(css_computed_style *style, uint8_t
 #undef FILL_OPACITY_MASK
 
 #define FLEX_BASIS_INDEX 7
-#define FLEX_BASIS_SHIFT 4
-#define FLEX_BASIS_MASK 0x7f0
+#define FLEX_BASIS_SHIFT 25
+#define FLEX_BASIS_MASK 0xfe000000
 
 static inline css_error set_flex_basis(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1105,9 +1105,9 @@ static inline css_error set_flex_basis(css_computed_style *style, uint8_t type,
 #undef FLEX_BASIS_SHIFT
 #undef FLEX_BASIS_MASK
 
-#define FLEX_DIRECTION_INDEX 13
-#define FLEX_DIRECTION_SHIFT 4
-#define FLEX_DIRECTION_MASK 0x70
+#define FLEX_DIRECTION_INDEX 9
+#define FLEX_DIRECTION_SHIFT 14
+#define FLEX_DIRECTION_MASK 0x1c000
 
 static inline css_error set_flex_direction(css_computed_style *style, uint8_t
 		type)
@@ -1124,9 +1124,9 @@ static inline css_error set_flex_direction(css_computed_style *style, uint8_t
 #undef FLEX_DIRECTION_SHIFT
 #undef FLEX_DIRECTION_MASK
 
-#define FLEX_GROW_INDEX 14
-#define FLEX_GROW_SHIFT 21
-#define FLEX_GROW_MASK 0x200000
+#define FLEX_GROW_INDEX 15
+#define FLEX_GROW_SHIFT 26
+#define FLEX_GROW_MASK 0x4000000
 
 static inline css_error set_flex_grow(css_computed_style *style, uint8_t type,
 		css_fixed fixed)
@@ -1145,9 +1145,9 @@ static inline css_error set_flex_grow(css_computed_style *style, uint8_t type,
 #undef FLEX_GROW_SHIFT
 #undef FLEX_GROW_MASK
 
-#define FLEX_SHRINK_INDEX 14
-#define FLEX_SHRINK_SHIFT 22
-#define FLEX_SHRINK_MASK 0x400000
+#define FLEX_SHRINK_INDEX 15
+#define FLEX_SHRINK_SHIFT 27
+#define FLEX_SHRINK_MASK 0x8000000
 
 static inline css_error set_flex_shrink(css_computed_style *style, uint8_t
 		type, css_fixed fixed)
@@ -1166,9 +1166,9 @@ static inline css_error set_flex_shrink(css_computed_style *style, uint8_t
 #undef FLEX_SHRINK_SHIFT
 #undef FLEX_SHRINK_MASK
 
-#define FLEX_WRAP_INDEX 11
-#define FLEX_WRAP_SHIFT 28
-#define FLEX_WRAP_MASK 0x30000000
+#define FLEX_WRAP_INDEX 13
+#define FLEX_WRAP_SHIFT 9
+#define FLEX_WRAP_MASK 0x600
 
 static inline css_error set_flex_wrap(css_computed_style *style, uint8_t type)
 {
@@ -1184,9 +1184,9 @@ static inline css_error set_flex_wrap(css_computed_style *style, uint8_t type)
 #undef FLEX_WRAP_SHIFT
 #undef FLEX_WRAP_MASK
 
-#define FLOAT_INDEX 11
-#define FLOAT_SHIFT 30
-#define FLOAT_MASK 0xc0000000
+#define FLOAT_INDEX 13
+#define FLOAT_SHIFT 11
+#define FLOAT_MASK 0x1800
 
 static inline css_error set_float(css_computed_style *style, uint8_t type)
 {
@@ -1201,9 +1201,9 @@ static inline css_error set_float(css_computed_style *style, uint8_t type)
 #undef FLOAT_SHIFT
 #undef FLOAT_MASK
 
-#define FONT_FAMILY_INDEX 13
-#define FONT_FAMILY_SHIFT 7
-#define FONT_FAMILY_MASK 0x380
+#define FONT_FAMILY_INDEX 9
+#define FONT_FAMILY_SHIFT 17
+#define FONT_FAMILY_MASK 0xe0000
 
 static inline css_error set_font_family(css_computed_style *style, uint8_t
 		type, lwc_string **string_arr)
@@ -1258,9 +1258,9 @@ static inline css_error set_font_size(css_computed_style *style, uint8_t type,
 #undef FONT_SIZE_SHIFT
 #undef FONT_SIZE_MASK
 
-#define FONT_STYLE_INDEX 10
-#define FONT_STYLE_SHIFT 0
-#define FONT_STYLE_MASK 0x3
+#define FONT_STYLE_INDEX 13
+#define FONT_STYLE_SHIFT 13
+#define FONT_STYLE_MASK 0x6000
 
 static inline css_error set_font_style(css_computed_style *style, uint8_t type)
 {
@@ -1276,9 +1276,9 @@ static inline css_error set_font_style(css_computed_style *style, uint8_t type)
 #undef FONT_STYLE_SHIFT
 #undef FONT_STYLE_MASK
 
-#define FONT_VARIANT_INDEX 10
-#define FONT_VARIANT_SHIFT 2
-#define FONT_VARIANT_MASK 0xc
+#define FONT_VARIANT_INDEX 13
+#define FONT_VARIANT_SHIFT 15
+#define FONT_VARIANT_MASK 0x18000
 
 static inline css_error set_font_variant(css_computed_style *style, uint8_t
 		type)
@@ -1295,7 +1295,7 @@ static inline css_error set_font_variant(css_computed_style *style, uint8_t
 #undef FONT_VARIANT_SHIFT
 #undef FONT_VARIANT_MASK
 
-#define FONT_WEIGHT_INDEX 6
+#define FONT_WEIGHT_INDEX 7
 #define FONT_WEIGHT_SHIFT 0
 #define FONT_WEIGHT_MASK 0xf
 
@@ -1313,9 +1313,298 @@ static inline css_error set_font_weight(css_computed_style *style, uint8_t type)
 #undef FONT_WEIGHT_SHIFT
 #undef FONT_WEIGHT_MASK
 
-#define HEIGHT_INDEX 7
-#define HEIGHT_SHIFT 11
-#define HEIGHT_MASK 0x3f800
+#define GRID_AUTO_COLUMNS_INDEX 15
+#define GRID_AUTO_COLUMNS_SHIFT 28
+#define GRID_AUTO_COLUMNS_MASK 0x10000000
+
+static inline css_error set_grid_auto_columns(css_computed_style *style,
+		uint8_t type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_AUTO_COLUMNS_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_AUTO_COLUMNS_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_AUTO_COLUMNS_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_auto_columns;
+	
+	if (string != NULL) {
+		style->i.grid_auto_columns = lwc_string_ref(string);
+	} else {
+		style->i.grid_auto_columns = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_AUTO_COLUMNS_INDEX
+#undef GRID_AUTO_COLUMNS_SHIFT
+#undef GRID_AUTO_COLUMNS_MASK
+
+#define GRID_AUTO_FLOW_INDEX 9
+#define GRID_AUTO_FLOW_SHIFT 20
+#define GRID_AUTO_FLOW_MASK 0x700000
+
+static inline css_error set_grid_auto_flow(css_computed_style *style, uint8_t
+		type)
+{
+	uint32_t *bits = &style->i.bits[GRID_AUTO_FLOW_INDEX];
+	
+	/* 3bits: ttt : type */
+	*bits = (*bits & ~GRID_AUTO_FLOW_MASK) | (((uint32_t)type & 0x7) <<
+			GRID_AUTO_FLOW_SHIFT);
+	
+	return CSS_OK;
+}
+#undef GRID_AUTO_FLOW_INDEX
+#undef GRID_AUTO_FLOW_SHIFT
+#undef GRID_AUTO_FLOW_MASK
+
+#define GRID_AUTO_ROWS_INDEX 15
+#define GRID_AUTO_ROWS_SHIFT 29
+#define GRID_AUTO_ROWS_MASK 0x20000000
+
+static inline css_error set_grid_auto_rows(css_computed_style *style, uint8_t
+		type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_AUTO_ROWS_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_AUTO_ROWS_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_AUTO_ROWS_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_auto_rows;
+	
+	if (string != NULL) {
+		style->i.grid_auto_rows = lwc_string_ref(string);
+	} else {
+		style->i.grid_auto_rows = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_AUTO_ROWS_INDEX
+#undef GRID_AUTO_ROWS_SHIFT
+#undef GRID_AUTO_ROWS_MASK
+
+#define GRID_COLUMN_END_INDEX 15
+#define GRID_COLUMN_END_SHIFT 30
+#define GRID_COLUMN_END_MASK 0x40000000
+
+static inline css_error set_grid_column_end(css_computed_style *style, uint8_t
+		type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_COLUMN_END_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_COLUMN_END_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_COLUMN_END_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_column_end;
+	
+	if (string != NULL) {
+		style->i.grid_column_end = lwc_string_ref(string);
+	} else {
+		style->i.grid_column_end = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_COLUMN_END_INDEX
+#undef GRID_COLUMN_END_SHIFT
+#undef GRID_COLUMN_END_MASK
+
+#define GRID_COLUMN_START_INDEX 15
+#define GRID_COLUMN_START_SHIFT 31
+#define GRID_COLUMN_START_MASK 0x80000000
+
+static inline css_error set_grid_column_start(css_computed_style *style,
+		uint8_t type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_COLUMN_START_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_COLUMN_START_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_COLUMN_START_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_column_start;
+	
+	if (string != NULL) {
+		style->i.grid_column_start = lwc_string_ref(string);
+	} else {
+		style->i.grid_column_start = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_COLUMN_START_INDEX
+#undef GRID_COLUMN_START_SHIFT
+#undef GRID_COLUMN_START_MASK
+
+#define GRID_ROW_END_INDEX 14
+#define GRID_ROW_END_SHIFT 0
+#define GRID_ROW_END_MASK 0x1
+
+static inline css_error set_grid_row_end(css_computed_style *style, uint8_t
+		type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_ROW_END_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_ROW_END_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_ROW_END_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_row_end;
+	
+	if (string != NULL) {
+		style->i.grid_row_end = lwc_string_ref(string);
+	} else {
+		style->i.grid_row_end = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_ROW_END_INDEX
+#undef GRID_ROW_END_SHIFT
+#undef GRID_ROW_END_MASK
+
+#define GRID_ROW_START_INDEX 14
+#define GRID_ROW_START_SHIFT 1
+#define GRID_ROW_START_MASK 0x2
+
+static inline css_error set_grid_row_start(css_computed_style *style, uint8_t
+		type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_ROW_START_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_ROW_START_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_ROW_START_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_row_start;
+	
+	if (string != NULL) {
+		style->i.grid_row_start = lwc_string_ref(string);
+	} else {
+		style->i.grid_row_start = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_ROW_START_INDEX
+#undef GRID_ROW_START_SHIFT
+#undef GRID_ROW_START_MASK
+
+#define GRID_TEMPLATE_AREAS_INDEX 14
+#define GRID_TEMPLATE_AREAS_SHIFT 2
+#define GRID_TEMPLATE_AREAS_MASK 0x4
+
+static inline css_error set_grid_template_areas(css_computed_style *style,
+		uint8_t type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_TEMPLATE_AREAS_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_TEMPLATE_AREAS_MASK) | (((uint32_t)type & 0x1)
+			<< GRID_TEMPLATE_AREAS_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_template_areas;
+	
+	if (string != NULL) {
+		style->i.grid_template_areas = lwc_string_ref(string);
+	} else {
+		style->i.grid_template_areas = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_TEMPLATE_AREAS_INDEX
+#undef GRID_TEMPLATE_AREAS_SHIFT
+#undef GRID_TEMPLATE_AREAS_MASK
+
+#define GRID_TEMPLATE_COLUMNS_INDEX 14
+#define GRID_TEMPLATE_COLUMNS_SHIFT 3
+#define GRID_TEMPLATE_COLUMNS_MASK 0x8
+
+static inline css_error set_grid_template_columns(css_computed_style *style,
+		uint8_t type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_TEMPLATE_COLUMNS_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_TEMPLATE_COLUMNS_MASK) | (((uint32_t)type & 0x1)
+			<< GRID_TEMPLATE_COLUMNS_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_template_columns;
+	
+	if (string != NULL) {
+		style->i.grid_template_columns = lwc_string_ref(string);
+	} else {
+		style->i.grid_template_columns = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_TEMPLATE_COLUMNS_INDEX
+#undef GRID_TEMPLATE_COLUMNS_SHIFT
+#undef GRID_TEMPLATE_COLUMNS_MASK
+
+#define GRID_TEMPLATE_ROWS_INDEX 14
+#define GRID_TEMPLATE_ROWS_SHIFT 4
+#define GRID_TEMPLATE_ROWS_MASK 0x10
+
+static inline css_error set_grid_template_rows(css_computed_style *style,
+		uint8_t type, lwc_string *string)
+{
+	uint32_t *bits = &style->i.bits[GRID_TEMPLATE_ROWS_INDEX];
+	
+	/* 1bit: t : type */
+	*bits = (*bits & ~GRID_TEMPLATE_ROWS_MASK) | (((uint32_t)type & 0x1) <<
+			GRID_TEMPLATE_ROWS_SHIFT);
+	
+	lwc_string *old_string = style->i.grid_template_rows;
+	
+	if (string != NULL) {
+		style->i.grid_template_rows = lwc_string_ref(string);
+	} else {
+		style->i.grid_template_rows = NULL;
+	}
+	
+	if (old_string != NULL)
+		lwc_string_unref(old_string);
+	
+	return CSS_OK;
+}
+#undef GRID_TEMPLATE_ROWS_INDEX
+#undef GRID_TEMPLATE_ROWS_SHIFT
+#undef GRID_TEMPLATE_ROWS_MASK
+
+#define HEIGHT_INDEX 6
+#define HEIGHT_SHIFT 4
+#define HEIGHT_MASK 0x7f0
 
 static inline css_error set_height(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1334,9 +1623,9 @@ static inline css_error set_height(css_computed_style *style, uint8_t type,
 #undef HEIGHT_SHIFT
 #undef HEIGHT_MASK
 
-#define JUSTIFY_CONTENT_INDEX 13
-#define JUSTIFY_CONTENT_SHIFT 10
-#define JUSTIFY_CONTENT_MASK 0x1c00
+#define JUSTIFY_CONTENT_INDEX 9
+#define JUSTIFY_CONTENT_SHIFT 23
+#define JUSTIFY_CONTENT_MASK 0x3800000
 
 static inline css_error set_justify_content(css_computed_style *style, uint8_t
 		type)
@@ -1353,9 +1642,47 @@ static inline css_error set_justify_content(css_computed_style *style, uint8_t
 #undef JUSTIFY_CONTENT_SHIFT
 #undef JUSTIFY_CONTENT_MASK
 
-#define LEFT_INDEX 7
-#define LEFT_SHIFT 18
-#define LEFT_MASK 0x1fc0000
+#define JUSTIFY_ITEMS_INDEX 6
+#define JUSTIFY_ITEMS_SHIFT 0
+#define JUSTIFY_ITEMS_MASK 0xf
+
+static inline css_error set_justify_items(css_computed_style *style, uint8_t
+		type)
+{
+	uint32_t *bits = &style->i.bits[JUSTIFY_ITEMS_INDEX];
+	
+	/* 4bits: tttt : type */
+	*bits = (*bits & ~JUSTIFY_ITEMS_MASK) | (((uint32_t)type & 0xf) <<
+			JUSTIFY_ITEMS_SHIFT);
+	
+	return CSS_OK;
+}
+#undef JUSTIFY_ITEMS_INDEX
+#undef JUSTIFY_ITEMS_SHIFT
+#undef JUSTIFY_ITEMS_MASK
+
+#define JUSTIFY_SELF_INDEX 5
+#define JUSTIFY_SELF_SHIFT 0
+#define JUSTIFY_SELF_MASK 0xf
+
+static inline css_error set_justify_self(css_computed_style *style, uint8_t
+		type)
+{
+	uint32_t *bits = &style->i.bits[JUSTIFY_SELF_INDEX];
+	
+	/* 4bits: tttt : type */
+	*bits = (*bits & ~JUSTIFY_SELF_MASK) | (((uint32_t)type & 0xf) <<
+			JUSTIFY_SELF_SHIFT);
+	
+	return CSS_OK;
+}
+#undef JUSTIFY_SELF_INDEX
+#undef JUSTIFY_SELF_SHIFT
+#undef JUSTIFY_SELF_MASK
+
+#define LEFT_INDEX 6
+#define LEFT_SHIFT 11
+#define LEFT_MASK 0x3f800
 
 static inline css_error set_left(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1374,9 +1701,9 @@ static inline css_error set_left(css_computed_style *style, uint8_t type,
 #undef LEFT_SHIFT
 #undef LEFT_MASK
 
-#define LETTER_SPACING_INDEX 7
-#define LETTER_SPACING_SHIFT 25
-#define LETTER_SPACING_MASK 0xfe000000
+#define LETTER_SPACING_INDEX 6
+#define LETTER_SPACING_SHIFT 18
+#define LETTER_SPACING_MASK 0x1fc0000
 
 static inline css_error set_letter_spacing(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1396,8 +1723,8 @@ static inline css_error set_letter_spacing(css_computed_style *style, uint8_t
 #undef LETTER_SPACING_MASK
 
 #define LINE_HEIGHT_INDEX 6
-#define LINE_HEIGHT_SHIFT 4
-#define LINE_HEIGHT_MASK 0x7f0
+#define LINE_HEIGHT_SHIFT 25
+#define LINE_HEIGHT_MASK 0xfe000000
 
 static inline css_error set_line_height(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1417,8 +1744,8 @@ static inline css_error set_line_height(css_computed_style *style, uint8_t
 #undef LINE_HEIGHT_MASK
 
 #define LIST_STYLE_IMAGE_INDEX 14
-#define LIST_STYLE_IMAGE_SHIFT 23
-#define LIST_STYLE_IMAGE_MASK 0x800000
+#define LIST_STYLE_IMAGE_SHIFT 5
+#define LIST_STYLE_IMAGE_MASK 0x20
 
 static inline css_error set_list_style_image(css_computed_style *style, uint8_t
 		type, lwc_string *string)
@@ -1446,9 +1773,9 @@ static inline css_error set_list_style_image(css_computed_style *style, uint8_t
 #undef LIST_STYLE_IMAGE_SHIFT
 #undef LIST_STYLE_IMAGE_MASK
 
-#define LIST_STYLE_POSITION_INDEX 10
-#define LIST_STYLE_POSITION_SHIFT 4
-#define LIST_STYLE_POSITION_MASK 0x30
+#define LIST_STYLE_POSITION_INDEX 13
+#define LIST_STYLE_POSITION_SHIFT 17
+#define LIST_STYLE_POSITION_MASK 0x60000
 
 static inline css_error set_list_style_position(css_computed_style *style,
 		uint8_t type)
@@ -1466,8 +1793,8 @@ static inline css_error set_list_style_position(css_computed_style *style,
 #undef LIST_STYLE_POSITION_MASK
 
 #define LIST_STYLE_TYPE_INDEX 8
-#define LIST_STYLE_TYPE_SHIFT 8
-#define LIST_STYLE_TYPE_MASK 0x3f00
+#define LIST_STYLE_TYPE_SHIFT 2
+#define LIST_STYLE_TYPE_MASK 0xfc
 
 static inline css_error set_list_style_type(css_computed_style *style, uint8_t
 		type)
@@ -1484,9 +1811,9 @@ static inline css_error set_list_style_type(css_computed_style *style, uint8_t
 #undef LIST_STYLE_TYPE_SHIFT
 #undef LIST_STYLE_TYPE_MASK
 
-#define MARGIN_BOTTOM_INDEX 6
-#define MARGIN_BOTTOM_SHIFT 11
-#define MARGIN_BOTTOM_MASK 0x3f800
+#define MARGIN_BOTTOM_INDEX 5
+#define MARGIN_BOTTOM_SHIFT 4
+#define MARGIN_BOTTOM_MASK 0x7f0
 
 static inline css_error set_margin_bottom(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1505,9 +1832,9 @@ static inline css_error set_margin_bottom(css_computed_style *style, uint8_t
 #undef MARGIN_BOTTOM_SHIFT
 #undef MARGIN_BOTTOM_MASK
 
-#define MARGIN_LEFT_INDEX 6
-#define MARGIN_LEFT_SHIFT 18
-#define MARGIN_LEFT_MASK 0x1fc0000
+#define MARGIN_LEFT_INDEX 5
+#define MARGIN_LEFT_SHIFT 11
+#define MARGIN_LEFT_MASK 0x3f800
 
 static inline css_error set_margin_left(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1526,9 +1853,9 @@ static inline css_error set_margin_left(css_computed_style *style, uint8_t
 #undef MARGIN_LEFT_SHIFT
 #undef MARGIN_LEFT_MASK
 
-#define MARGIN_RIGHT_INDEX 6
-#define MARGIN_RIGHT_SHIFT 25
-#define MARGIN_RIGHT_MASK 0xfe000000
+#define MARGIN_RIGHT_INDEX 5
+#define MARGIN_RIGHT_SHIFT 18
+#define MARGIN_RIGHT_MASK 0x1fc0000
 
 static inline css_error set_margin_right(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1548,8 +1875,8 @@ static inline css_error set_margin_right(css_computed_style *style, uint8_t
 #undef MARGIN_RIGHT_MASK
 
 #define MARGIN_TOP_INDEX 5
-#define MARGIN_TOP_SHIFT 4
-#define MARGIN_TOP_MASK 0x7f0
+#define MARGIN_TOP_SHIFT 25
+#define MARGIN_TOP_MASK 0xfe000000
 
 static inline css_error set_margin_top(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1568,9 +1895,9 @@ static inline css_error set_margin_top(css_computed_style *style, uint8_t type,
 #undef MARGIN_TOP_SHIFT
 #undef MARGIN_TOP_MASK
 
-#define MAX_HEIGHT_INDEX 5
-#define MAX_HEIGHT_SHIFT 11
-#define MAX_HEIGHT_MASK 0x3f800
+#define MAX_HEIGHT_INDEX 4
+#define MAX_HEIGHT_SHIFT 4
+#define MAX_HEIGHT_MASK 0x7f0
 
 static inline css_error set_max_height(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1589,9 +1916,9 @@ static inline css_error set_max_height(css_computed_style *style, uint8_t type,
 #undef MAX_HEIGHT_SHIFT
 #undef MAX_HEIGHT_MASK
 
-#define MAX_WIDTH_INDEX 5
-#define MAX_WIDTH_SHIFT 18
-#define MAX_WIDTH_MASK 0x1fc0000
+#define MAX_WIDTH_INDEX 4
+#define MAX_WIDTH_SHIFT 11
+#define MAX_WIDTH_MASK 0x3f800
 
 static inline css_error set_max_width(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1610,9 +1937,9 @@ static inline css_error set_max_width(css_computed_style *style, uint8_t type,
 #undef MAX_WIDTH_SHIFT
 #undef MAX_WIDTH_MASK
 
-#define MIN_HEIGHT_INDEX 5
-#define MIN_HEIGHT_SHIFT 25
-#define MIN_HEIGHT_MASK 0xfe000000
+#define MIN_HEIGHT_INDEX 4
+#define MIN_HEIGHT_SHIFT 18
+#define MIN_HEIGHT_MASK 0x1fc0000
 
 static inline css_error set_min_height(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1632,8 +1959,8 @@ static inline css_error set_min_height(css_computed_style *style, uint8_t type,
 #undef MIN_HEIGHT_MASK
 
 #define MIN_WIDTH_INDEX 4
-#define MIN_WIDTH_SHIFT 4
-#define MIN_WIDTH_MASK 0x7f0
+#define MIN_WIDTH_SHIFT 25
+#define MIN_WIDTH_MASK 0xfe000000
 
 static inline css_error set_min_width(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -1653,8 +1980,8 @@ static inline css_error set_min_width(css_computed_style *style, uint8_t type,
 #undef MIN_WIDTH_MASK
 
 #define OPACITY_INDEX 14
-#define OPACITY_SHIFT 24
-#define OPACITY_MASK 0x1000000
+#define OPACITY_SHIFT 6
+#define OPACITY_MASK 0x40
 
 static inline css_error set_opacity(css_computed_style *style, uint8_t type,
 		css_fixed fixed)
@@ -1674,8 +2001,8 @@ static inline css_error set_opacity(css_computed_style *style, uint8_t type,
 #undef OPACITY_MASK
 
 #define ORDER_INDEX 14
-#define ORDER_SHIFT 25
-#define ORDER_MASK 0x2000000
+#define ORDER_SHIFT 7
+#define ORDER_MASK 0x80
 
 static inline css_error set_order(css_computed_style *style, uint8_t type,
 		int32_t integer)
@@ -1693,9 +2020,9 @@ static inline css_error set_order(css_computed_style *style, uint8_t type,
 #undef ORDER_SHIFT
 #undef ORDER_MASK
 
-#define ORPHANS_INDEX 14
-#define ORPHANS_SHIFT 26
-#define ORPHANS_MASK 0x4000000
+#define ORPHANS_INDEX 13
+#define ORPHANS_SHIFT 0
+#define ORPHANS_MASK 0x1
 
 static inline css_error set_orphans(css_computed_style *style, uint8_t type,
 		int32_t integer)
@@ -1714,9 +2041,9 @@ static inline css_error set_orphans(css_computed_style *style, uint8_t type,
 #undef ORPHANS_SHIFT
 #undef ORPHANS_MASK
 
-#define OUTLINE_COLOR_INDEX 10
-#define OUTLINE_COLOR_SHIFT 6
-#define OUTLINE_COLOR_MASK 0xc0
+#define OUTLINE_COLOR_INDEX 13
+#define OUTLINE_COLOR_SHIFT 19
+#define OUTLINE_COLOR_MASK 0x180000
 
 static inline css_error set_outline_color(css_computed_style *style, uint8_t
 		type, css_color color)
@@ -1735,7 +2062,7 @@ static inline css_error set_outline_color(css_computed_style *style, uint8_t
 #undef OUTLINE_COLOR_SHIFT
 #undef OUTLINE_COLOR_MASK
 
-#define OUTLINE_STYLE_INDEX 5
+#define OUTLINE_STYLE_INDEX 4
 #define OUTLINE_STYLE_SHIFT 0
 #define OUTLINE_STYLE_MASK 0xf
 
@@ -1775,9 +2102,9 @@ static inline css_error set_outline_width(css_computed_style *style, uint8_t
 #undef OUTLINE_WIDTH_SHIFT
 #undef OUTLINE_WIDTH_MASK
 
-#define OVERFLOW_X_INDEX 13
-#define OVERFLOW_X_SHIFT 13
-#define OVERFLOW_X_MASK 0xe000
+#define OVERFLOW_X_INDEX 9
+#define OVERFLOW_X_SHIFT 26
+#define OVERFLOW_X_MASK 0x1c000000
 
 static inline css_error set_overflow_x(css_computed_style *style, uint8_t type)
 {
@@ -1793,9 +2120,9 @@ static inline css_error set_overflow_x(css_computed_style *style, uint8_t type)
 #undef OVERFLOW_X_SHIFT
 #undef OVERFLOW_X_MASK
 
-#define OVERFLOW_Y_INDEX 13
-#define OVERFLOW_Y_SHIFT 16
-#define OVERFLOW_Y_MASK 0x70000
+#define OVERFLOW_Y_INDEX 9
+#define OVERFLOW_Y_SHIFT 29
+#define OVERFLOW_Y_MASK 0xe0000000
 
 static inline css_error set_overflow_y(css_computed_style *style, uint8_t type)
 {
@@ -1812,8 +2139,8 @@ static inline css_error set_overflow_y(css_computed_style *style, uint8_t type)
 #undef OVERFLOW_Y_MASK
 
 #define PADDING_BOTTOM_INDEX 8
-#define PADDING_BOTTOM_SHIFT 14
-#define PADDING_BOTTOM_MASK 0xfc000
+#define PADDING_BOTTOM_SHIFT 8
+#define PADDING_BOTTOM_MASK 0x3f00
 
 static inline css_error set_padding_bottom(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1833,8 +2160,8 @@ static inline css_error set_padding_bottom(css_computed_style *style, uint8_t
 #undef PADDING_BOTTOM_MASK
 
 #define PADDING_LEFT_INDEX 8
-#define PADDING_LEFT_SHIFT 20
-#define PADDING_LEFT_MASK 0x3f00000
+#define PADDING_LEFT_SHIFT 14
+#define PADDING_LEFT_MASK 0xfc000
 
 static inline css_error set_padding_left(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1854,8 +2181,8 @@ static inline css_error set_padding_left(css_computed_style *style, uint8_t
 #undef PADDING_LEFT_MASK
 
 #define PADDING_RIGHT_INDEX 8
-#define PADDING_RIGHT_SHIFT 26
-#define PADDING_RIGHT_MASK 0xfc000000
+#define PADDING_RIGHT_SHIFT 20
+#define PADDING_RIGHT_MASK 0x3f00000
 
 static inline css_error set_padding_right(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1874,9 +2201,9 @@ static inline css_error set_padding_right(css_computed_style *style, uint8_t
 #undef PADDING_RIGHT_SHIFT
 #undef PADDING_RIGHT_MASK
 
-#define PADDING_TOP_INDEX 3
-#define PADDING_TOP_SHIFT 5
-#define PADDING_TOP_MASK 0x7e0
+#define PADDING_TOP_INDEX 8
+#define PADDING_TOP_SHIFT 26
+#define PADDING_TOP_MASK 0xfc000000
 
 static inline css_error set_padding_top(css_computed_style *style, uint8_t
 		type, css_fixed length, css_unit unit)
@@ -1895,9 +2222,9 @@ static inline css_error set_padding_top(css_computed_style *style, uint8_t
 #undef PADDING_TOP_SHIFT
 #undef PADDING_TOP_MASK
 
-#define PAGE_BREAK_AFTER_INDEX 13
-#define PAGE_BREAK_AFTER_SHIFT 19
-#define PAGE_BREAK_AFTER_MASK 0x380000
+#define PAGE_BREAK_AFTER_INDEX 12
+#define PAGE_BREAK_AFTER_SHIFT 1
+#define PAGE_BREAK_AFTER_MASK 0xe
 
 static inline css_error set_page_break_after(css_computed_style *style, uint8_t
 		type)
@@ -1914,9 +2241,9 @@ static inline css_error set_page_break_after(css_computed_style *style, uint8_t
 #undef PAGE_BREAK_AFTER_SHIFT
 #undef PAGE_BREAK_AFTER_MASK
 
-#define PAGE_BREAK_BEFORE_INDEX 13
-#define PAGE_BREAK_BEFORE_SHIFT 22
-#define PAGE_BREAK_BEFORE_MASK 0x1c00000
+#define PAGE_BREAK_BEFORE_INDEX 12
+#define PAGE_BREAK_BEFORE_SHIFT 4
+#define PAGE_BREAK_BEFORE_MASK 0x70
 
 static inline css_error set_page_break_before(css_computed_style *style,
 		uint8_t type)
@@ -1933,9 +2260,9 @@ static inline css_error set_page_break_before(css_computed_style *style,
 #undef PAGE_BREAK_BEFORE_SHIFT
 #undef PAGE_BREAK_BEFORE_MASK
 
-#define PAGE_BREAK_INSIDE_INDEX 10
-#define PAGE_BREAK_INSIDE_SHIFT 8
-#define PAGE_BREAK_INSIDE_MASK 0x300
+#define PAGE_BREAK_INSIDE_INDEX 13
+#define PAGE_BREAK_INSIDE_SHIFT 21
+#define PAGE_BREAK_INSIDE_MASK 0x600000
 
 static inline css_error set_page_break_inside(css_computed_style *style,
 		uint8_t type)
@@ -1952,9 +2279,9 @@ static inline css_error set_page_break_inside(css_computed_style *style,
 #undef PAGE_BREAK_INSIDE_SHIFT
 #undef PAGE_BREAK_INSIDE_MASK
 
-#define POSITION_INDEX 13
-#define POSITION_SHIFT 25
-#define POSITION_MASK 0xe000000
+#define POSITION_INDEX 12
+#define POSITION_SHIFT 7
+#define POSITION_MASK 0x380
 
 static inline css_error set_position(css_computed_style *style, uint8_t type)
 {
@@ -1970,9 +2297,9 @@ static inline css_error set_position(css_computed_style *style, uint8_t type)
 #undef POSITION_SHIFT
 #undef POSITION_MASK
 
-#define QUOTES_INDEX 14
-#define QUOTES_SHIFT 27
-#define QUOTES_MASK 0x8000000
+#define QUOTES_INDEX 12
+#define QUOTES_SHIFT 0
+#define QUOTES_MASK 0x1
 
 static inline css_error set_quotes(css_computed_style *style, uint8_t type,
 		lwc_string **string_arr)
@@ -2006,9 +2333,9 @@ static inline css_error set_quotes(css_computed_style *style, uint8_t type,
 #undef QUOTES_SHIFT
 #undef QUOTES_MASK
 
-#define RIGHT_INDEX 4
-#define RIGHT_SHIFT 11
-#define RIGHT_MASK 0x3f800
+#define RIGHT_INDEX 3
+#define RIGHT_SHIFT 4
+#define RIGHT_MASK 0x7f0
 
 static inline css_error set_right(css_computed_style *style, uint8_t type,
 		css_fixed length, css_unit unit)
@@ -2027,7 +2354,28 @@ static inline css_error set_right(css_computed_style *style, uint8_t type,
 #undef RIGHT_SHIFT
 #undef RIGHT_MASK
 
-#define STROKE_OPACITY_INDEX 13
+#define ROW_GAP_INDEX 3
+#define ROW_GAP_SHIFT 11
+#define ROW_GAP_MASK 0x3f800
+
+static inline css_error set_row_gap(css_computed_style *style, uint8_t type,
+		css_fixed length, css_unit unit)
+{
+	uint32_t *bits = &style->i.bits[ROW_GAP_INDEX];
+	
+	/* 7bits: uuuuutt : unit | type */
+	*bits = (*bits & ~ROW_GAP_MASK) | ((((uint32_t)type & 0x3) | (unit <<
+			2)) << ROW_GAP_SHIFT);
+	
+	style->i.row_gap = length;
+	
+	return CSS_OK;
+}
+#undef ROW_GAP_INDEX
+#undef ROW_GAP_SHIFT
+#undef ROW_GAP_MASK
+
+#define STROKE_OPACITY_INDEX 11
 #define STROKE_OPACITY_SHIFT 0
 #define STROKE_OPACITY_MASK 0x1
 
@@ -2048,9 +2396,9 @@ static inline css_error set_stroke_opacity(css_computed_style *style, uint8_t
 #undef STROKE_OPACITY_SHIFT
 #undef STROKE_OPACITY_MASK
 
-#define TABLE_LAYOUT_INDEX 10
-#define TABLE_LAYOUT_SHIFT 10
-#define TABLE_LAYOUT_MASK 0xc00
+#define TABLE_LAYOUT_INDEX 13
+#define TABLE_LAYOUT_SHIFT 23
+#define TABLE_LAYOUT_MASK 0x1800000
 
 static inline css_error set_table_layout(css_computed_style *style, uint8_t
 		type)
@@ -2067,7 +2415,7 @@ static inline css_error set_table_layout(css_computed_style *style, uint8_t
 #undef TABLE_LAYOUT_SHIFT
 #undef TABLE_LAYOUT_MASK
 
-#define TEXT_ALIGN_INDEX 4
+#define TEXT_ALIGN_INDEX 3
 #define TEXT_ALIGN_SHIFT 0
 #define TEXT_ALIGN_MASK 0xf
 
@@ -2085,9 +2433,9 @@ static inline css_error set_text_align(css_computed_style *style, uint8_t type)
 #undef TEXT_ALIGN_SHIFT
 #undef TEXT_ALIGN_MASK
 
-#define TEXT_DECORATION_INDEX 3
-#define TEXT_DECORATION_SHIFT 0
-#define TEXT_DECORATION_MASK 0x1f
+#define TEXT_DECORATION_INDEX 11
+#define TEXT_DECORATION_SHIFT 27
+#define TEXT_DECORATION_MASK 0xf8000000
 
 static inline css_error set_text_decoration(css_computed_style *style, uint8_t
 		type)
@@ -2125,9 +2473,9 @@ static inline css_error set_text_indent(css_computed_style *style, uint8_t
 #undef TEXT_INDENT_SHIFT
 #undef TEXT_INDENT_MASK
 
-#define TEXT_TRANSFORM_INDEX 9
-#define TEXT_TRANSFORM_SHIFT 0
-#define TEXT_TRANSFORM_MASK 0x7
+#define TEXT_TRANSFORM_INDEX 12
+#define TEXT_TRANSFORM_SHIFT 10
+#define TEXT_TRANSFORM_MASK 0x1c00
 
 static inline css_error set_text_transform(css_computed_style *style, uint8_t
 		type)
@@ -2144,7 +2492,7 @@ static inline css_error set_text_transform(css_computed_style *style, uint8_t
 #undef TEXT_TRANSFORM_SHIFT
 #undef TEXT_TRANSFORM_MASK
 
-#define TOP_INDEX 4
+#define TOP_INDEX 3
 #define TOP_SHIFT 18
 #define TOP_MASK 0x1fc0000
 
@@ -2165,9 +2513,9 @@ static inline css_error set_top(css_computed_style *style, uint8_t type,
 #undef TOP_SHIFT
 #undef TOP_MASK
 
-#define UNICODE_BIDI_INDEX 10
-#define UNICODE_BIDI_SHIFT 12
-#define UNICODE_BIDI_MASK 0x3000
+#define UNICODE_BIDI_INDEX 13
+#define UNICODE_BIDI_SHIFT 25
+#define UNICODE_BIDI_MASK 0x6000000
 
 static inline css_error set_unicode_bidi(css_computed_style *style, uint8_t
 		type)
@@ -2184,7 +2532,7 @@ static inline css_error set_unicode_bidi(css_computed_style *style, uint8_t
 #undef UNICODE_BIDI_SHIFT
 #undef UNICODE_BIDI_MASK
 
-#define VERTICAL_ALIGN_INDEX 12
+#define VERTICAL_ALIGN_INDEX 10
 #define VERTICAL_ALIGN_SHIFT 1
 #define VERTICAL_ALIGN_MASK 0x3fe
 
@@ -2205,9 +2553,9 @@ static inline css_error set_vertical_align(css_computed_style *style, uint8_t
 #undef VERTICAL_ALIGN_SHIFT
 #undef VERTICAL_ALIGN_MASK
 
-#define VISIBILITY_INDEX 10
-#define VISIBILITY_SHIFT 14
-#define VISIBILITY_MASK 0xc000
+#define VISIBILITY_INDEX 13
+#define VISIBILITY_SHIFT 27
+#define VISIBILITY_MASK 0x18000000
 
 static inline css_error set_visibility(css_computed_style *style, uint8_t type)
 {
@@ -2223,9 +2571,9 @@ static inline css_error set_visibility(css_computed_style *style, uint8_t type)
 #undef VISIBILITY_SHIFT
 #undef VISIBILITY_MASK
 
-#define WHITE_SPACE_INDEX 8
-#define WHITE_SPACE_SHIFT 0
-#define WHITE_SPACE_MASK 0x7
+#define WHITE_SPACE_INDEX 12
+#define WHITE_SPACE_SHIFT 13
+#define WHITE_SPACE_MASK 0xe000
 
 static inline css_error set_white_space(css_computed_style *style, uint8_t type)
 {
@@ -2241,7 +2589,7 @@ static inline css_error set_white_space(css_computed_style *style, uint8_t type)
 #undef WHITE_SPACE_SHIFT
 #undef WHITE_SPACE_MASK
 
-#define WIDOWS_INDEX 12
+#define WIDOWS_INDEX 10
 #define WIDOWS_SHIFT 0
 #define WIDOWS_MASK 0x1
 
@@ -2262,7 +2610,7 @@ static inline css_error set_widows(css_computed_style *style, uint8_t type,
 #undef WIDOWS_SHIFT
 #undef WIDOWS_MASK
 
-#define WIDTH_INDEX 4
+#define WIDTH_INDEX 3
 #define WIDTH_SHIFT 25
 #define WIDTH_MASK 0xfe000000
 
@@ -2304,9 +2652,9 @@ static inline css_error set_word_spacing(css_computed_style *style, uint8_t
 #undef WORD_SPACING_SHIFT
 #undef WORD_SPACING_MASK
 
-#define WRITING_MODE_INDEX 10
-#define WRITING_MODE_SHIFT 16
-#define WRITING_MODE_MASK 0x30000
+#define WRITING_MODE_INDEX 9
+#define WRITING_MODE_SHIFT 0
+#define WRITING_MODE_MASK 0x3
 
 static inline css_error set_writing_mode(css_computed_style *style, uint8_t
 		type)
@@ -2323,9 +2671,9 @@ static inline css_error set_writing_mode(css_computed_style *style, uint8_t
 #undef WRITING_MODE_SHIFT
 #undef WRITING_MODE_MASK
 
-#define Z_INDEX_INDEX 10
-#define Z_INDEX_SHIFT 18
-#define Z_INDEX_MASK 0xc0000
+#define Z_INDEX_INDEX 8
+#define Z_INDEX_SHIFT 0
+#define Z_INDEX_MASK 0x3
 
 static inline css_error set_z_index(css_computed_style *style, uint8_t type,
 		int32_t integer)
