$NetBSD$

CSS grid, box alignment keywords, gradients, border radii, shadows, calc() and ::first-letter: parse, cascade and compute them.

--- src/select/autogenerated_propget.h.orig
+++ src/select/autogenerated_propget.h
@@ -6,9 +6,9 @@
  */
 
 
-#define ALIGN_CONTENT_INDEX 10
-#define ALIGN_CONTENT_SHIFT 20
-#define ALIGN_CONTENT_MASK 0x700000
+#define ALIGN_CONTENT_INDEX 13
+#define ALIGN_CONTENT_SHIFT 29
+#define ALIGN_CONTENT_MASK 0xe0000000
 static inline uint8_t get_align_content_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[ALIGN_CONTENT_INDEX];
@@ -32,9 +32,9 @@ static inline uint8_t get_align_content(const css_computed_style *style)
 #undef ALIGN_CONTENT_SHIFT
 #undef ALIGN_CONTENT_MASK
 
-#define ALIGN_ITEMS_INDEX 10
-#define ALIGN_ITEMS_SHIFT 23
-#define ALIGN_ITEMS_MASK 0x3800000
+#define ALIGN_ITEMS_INDEX 9
+#define ALIGN_ITEMS_SHIFT 2
+#define ALIGN_ITEMS_MASK 0x1c
 static inline uint8_t get_align_items_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[ALIGN_ITEMS_INDEX];
@@ -58,9 +58,9 @@ static inline uint8_t get_align_items(const css_computed_style *style)
 #undef ALIGN_ITEMS_SHIFT
 #undef ALIGN_ITEMS_MASK
 
-#define ALIGN_SELF_INDEX 10
-#define ALIGN_SELF_SHIFT 26
-#define ALIGN_SELF_MASK 0x1c000000
+#define ALIGN_SELF_INDEX 9
+#define ALIGN_SELF_SHIFT 5
+#define ALIGN_SELF_MASK 0xe0
 static inline uint8_t get_align_self_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[ALIGN_SELF_INDEX];
@@ -85,8 +85,8 @@ static inline uint8_t get_align_self(const css_computed_style *style)
 #undef ALIGN_SELF_MASK
 
 #define BACKGROUND_ATTACHMENT_INDEX 14
-#define BACKGROUND_ATTACHMENT_SHIFT 28
-#define BACKGROUND_ATTACHMENT_MASK 0x30000000
+#define BACKGROUND_ATTACHMENT_SHIFT 8
+#define BACKGROUND_ATTACHMENT_MASK 0x300
 static inline uint8_t get_background_attachment_bits(const css_computed_style
 		*style)
 {
@@ -112,8 +112,8 @@ static inline uint8_t get_background_attachment(const css_computed_style *style)
 #undef BACKGROUND_ATTACHMENT_MASK
 
 #define BACKGROUND_COLOR_INDEX 14
-#define BACKGROUND_COLOR_SHIFT 30
-#define BACKGROUND_COLOR_MASK 0xc0000000
+#define BACKGROUND_COLOR_SHIFT 10
+#define BACKGROUND_COLOR_MASK 0xc00
 static inline uint8_t get_background_color_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BACKGROUND_COLOR_INDEX];
@@ -139,9 +139,9 @@ static inline uint8_t get_background_color(const css_computed_style *style,
 #undef BACKGROUND_COLOR_SHIFT
 #undef BACKGROUND_COLOR_MASK
 
-#define BACKGROUND_IMAGE_INDEX 14
-#define BACKGROUND_IMAGE_SHIFT 16
-#define BACKGROUND_IMAGE_MASK 0x10000
+#define BACKGROUND_IMAGE_INDEX 15
+#define BACKGROUND_IMAGE_SHIFT 15
+#define BACKGROUND_IMAGE_MASK 0x8000
 static inline uint8_t get_background_image_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BACKGROUND_IMAGE_INDEX];
@@ -167,7 +167,7 @@ static inline uint8_t get_background_image(const css_computed_style *style,
 #undef BACKGROUND_IMAGE_SHIFT
 #undef BACKGROUND_IMAGE_MASK
 
-#define BACKGROUND_POSITION_INDEX 12
+#define BACKGROUND_POSITION_INDEX 10
 #define BACKGROUND_POSITION_SHIFT 10
 #define BACKGROUND_POSITION_MASK 0x1ffc00
 static inline uint8_t get_background_position_bits(const css_computed_style
@@ -202,9 +202,9 @@ static inline uint8_t get_background_position(const css_computed_style *style,
 #undef BACKGROUND_POSITION_SHIFT
 #undef BACKGROUND_POSITION_MASK
 
-#define BACKGROUND_REPEAT_INDEX 10
-#define BACKGROUND_REPEAT_SHIFT 29
-#define BACKGROUND_REPEAT_MASK 0xe0000000
+#define BACKGROUND_REPEAT_INDEX 9
+#define BACKGROUND_REPEAT_SHIFT 8
+#define BACKGROUND_REPEAT_MASK 0x700
 static inline uint8_t get_background_repeat_bits(const css_computed_style
 		*style)
 {
@@ -229,9 +229,9 @@ static inline uint8_t get_background_repeat(const css_computed_style *style)
 #undef BACKGROUND_REPEAT_SHIFT
 #undef BACKGROUND_REPEAT_MASK
 
-#define BORDER_BOTTOM_COLOR_INDEX 11
-#define BORDER_BOTTOM_COLOR_SHIFT 0
-#define BORDER_BOTTOM_COLOR_MASK 0x3
+#define BORDER_BOTTOM_COLOR_INDEX 14
+#define BORDER_BOTTOM_COLOR_SHIFT 12
+#define BORDER_BOTTOM_COLOR_MASK 0x3000
 static inline uint8_t get_border_bottom_color_bits(const css_computed_style
 		*style)
 {
@@ -258,9 +258,67 @@ static inline uint8_t get_border_bottom_color(const css_computed_style *style,
 #undef BORDER_BOTTOM_COLOR_SHIFT
 #undef BORDER_BOTTOM_COLOR_MASK
 
-#define BORDER_BOTTOM_STYLE_INDEX 13
-#define BORDER_BOTTOM_STYLE_SHIFT 28
-#define BORDER_BOTTOM_STYLE_MASK 0xf0000000
+#define BORDER_BOTTOM_LEFT_RADIUS_INDEX 15
+#define BORDER_BOTTOM_LEFT_RADIUS_SHIFT 16
+#define BORDER_BOTTOM_LEFT_RADIUS_MASK 0x10000
+static inline uint8_t get_border_bottom_left_radius_bits(const
+		css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[BORDER_BOTTOM_LEFT_RADIUS_INDEX];
+	bits &= BORDER_BOTTOM_LEFT_RADIUS_MASK;
+	bits >>= BORDER_BOTTOM_LEFT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_border_bottom_left_radius(const css_computed_style
+		*style, lwc_string **string)
+{
+	uint32_t bits = style->i.bits[BORDER_BOTTOM_LEFT_RADIUS_INDEX];
+	bits &= BORDER_BOTTOM_LEFT_RADIUS_MASK;
+	bits >>= BORDER_BOTTOM_LEFT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.border_bottom_left_radius;
+	
+	return (bits & 0x1);
+}
+#undef BORDER_BOTTOM_LEFT_RADIUS_INDEX
+#undef BORDER_BOTTOM_LEFT_RADIUS_SHIFT
+#undef BORDER_BOTTOM_LEFT_RADIUS_MASK
+
+#define BORDER_BOTTOM_RIGHT_RADIUS_INDEX 15
+#define BORDER_BOTTOM_RIGHT_RADIUS_SHIFT 17
+#define BORDER_BOTTOM_RIGHT_RADIUS_MASK 0x20000
+static inline uint8_t get_border_bottom_right_radius_bits(const
+		css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[BORDER_BOTTOM_RIGHT_RADIUS_INDEX];
+	bits &= BORDER_BOTTOM_RIGHT_RADIUS_MASK;
+	bits >>= BORDER_BOTTOM_RIGHT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_border_bottom_right_radius(const css_computed_style
+		*style, lwc_string **string)
+{
+	uint32_t bits = style->i.bits[BORDER_BOTTOM_RIGHT_RADIUS_INDEX];
+	bits &= BORDER_BOTTOM_RIGHT_RADIUS_MASK;
+	bits >>= BORDER_BOTTOM_RIGHT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.border_bottom_right_radius;
+	
+	return (bits & 0x1);
+}
+#undef BORDER_BOTTOM_RIGHT_RADIUS_INDEX
+#undef BORDER_BOTTOM_RIGHT_RADIUS_SHIFT
+#undef BORDER_BOTTOM_RIGHT_RADIUS_MASK
+
+#define BORDER_BOTTOM_STYLE_INDEX 12
+#define BORDER_BOTTOM_STYLE_SHIFT 16
+#define BORDER_BOTTOM_STYLE_MASK 0xf0000
 static inline uint8_t get_border_bottom_style_bits(const css_computed_style
 		*style)
 {
@@ -317,9 +375,9 @@ static inline uint8_t get_border_bottom_width(const css_computed_style *style,
 #undef BORDER_BOTTOM_WIDTH_SHIFT
 #undef BORDER_BOTTOM_WIDTH_MASK
 
-#define BORDER_COLLAPSE_INDEX 11
-#define BORDER_COLLAPSE_SHIFT 2
-#define BORDER_COLLAPSE_MASK 0xc
+#define BORDER_COLLAPSE_INDEX 14
+#define BORDER_COLLAPSE_SHIFT 14
+#define BORDER_COLLAPSE_MASK 0xc000
 static inline uint8_t get_border_collapse_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BORDER_COLLAPSE_INDEX];
@@ -343,9 +401,9 @@ static inline uint8_t get_border_collapse(const css_computed_style *style)
 #undef BORDER_COLLAPSE_SHIFT
 #undef BORDER_COLLAPSE_MASK
 
-#define BORDER_LEFT_COLOR_INDEX 11
-#define BORDER_LEFT_COLOR_SHIFT 4
-#define BORDER_LEFT_COLOR_MASK 0x30
+#define BORDER_LEFT_COLOR_INDEX 14
+#define BORDER_LEFT_COLOR_SHIFT 16
+#define BORDER_LEFT_COLOR_MASK 0x30000
 static inline uint8_t get_border_left_color_bits(const css_computed_style
 		*style)
 {
@@ -372,9 +430,9 @@ static inline uint8_t get_border_left_color(const css_computed_style *style,
 #undef BORDER_LEFT_COLOR_SHIFT
 #undef BORDER_LEFT_COLOR_MASK
 
-#define BORDER_LEFT_STYLE_INDEX 9
-#define BORDER_LEFT_STYLE_SHIFT 3
-#define BORDER_LEFT_STYLE_MASK 0x78
+#define BORDER_LEFT_STYLE_INDEX 12
+#define BORDER_LEFT_STYLE_SHIFT 20
+#define BORDER_LEFT_STYLE_MASK 0xf00000
 static inline uint8_t get_border_left_style_bits(const css_computed_style
 		*style)
 {
@@ -431,9 +489,9 @@ static inline uint8_t get_border_left_width(const css_computed_style *style,
 #undef BORDER_LEFT_WIDTH_SHIFT
 #undef BORDER_LEFT_WIDTH_MASK
 
-#define BORDER_RIGHT_COLOR_INDEX 11
-#define BORDER_RIGHT_COLOR_SHIFT 6
-#define BORDER_RIGHT_COLOR_MASK 0xc0
+#define BORDER_RIGHT_COLOR_INDEX 14
+#define BORDER_RIGHT_COLOR_SHIFT 18
+#define BORDER_RIGHT_COLOR_MASK 0xc0000
 static inline uint8_t get_border_right_color_bits(const css_computed_style
 		*style)
 {
@@ -460,9 +518,9 @@ static inline uint8_t get_border_right_color(const css_computed_style *style,
 #undef BORDER_RIGHT_COLOR_SHIFT
 #undef BORDER_RIGHT_COLOR_MASK
 
-#define BORDER_RIGHT_STYLE_INDEX 9
-#define BORDER_RIGHT_STYLE_SHIFT 7
-#define BORDER_RIGHT_STYLE_MASK 0x780
+#define BORDER_RIGHT_STYLE_INDEX 12
+#define BORDER_RIGHT_STYLE_SHIFT 24
+#define BORDER_RIGHT_STYLE_MASK 0xf000000
 static inline uint8_t get_border_right_style_bits(const css_computed_style
 		*style)
 {
@@ -519,7 +577,7 @@ static inline uint8_t get_border_right_width(const css_computed_style *style,
 #undef BORDER_RIGHT_WIDTH_SHIFT
 #undef BORDER_RIGHT_WIDTH_MASK
 
-#define BORDER_SPACING_INDEX 12
+#define BORDER_SPACING_INDEX 10
 #define BORDER_SPACING_SHIFT 21
 #define BORDER_SPACING_MASK 0xffe00000
 static inline uint8_t get_border_spacing_bits(const css_computed_style *style)
@@ -553,9 +611,9 @@ static inline uint8_t get_border_spacing(const css_computed_style *style,
 #undef BORDER_SPACING_SHIFT
 #undef BORDER_SPACING_MASK
 
-#define BORDER_TOP_COLOR_INDEX 11
-#define BORDER_TOP_COLOR_SHIFT 8
-#define BORDER_TOP_COLOR_MASK 0x300
+#define BORDER_TOP_COLOR_INDEX 14
+#define BORDER_TOP_COLOR_SHIFT 20
+#define BORDER_TOP_COLOR_MASK 0x300000
 static inline uint8_t get_border_top_color_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BORDER_TOP_COLOR_INDEX];
@@ -581,9 +639,67 @@ static inline uint8_t get_border_top_color(const css_computed_style *style,
 #undef BORDER_TOP_COLOR_SHIFT
 #undef BORDER_TOP_COLOR_MASK
 
-#define BORDER_TOP_STYLE_INDEX 9
-#define BORDER_TOP_STYLE_SHIFT 11
-#define BORDER_TOP_STYLE_MASK 0x7800
+#define BORDER_TOP_LEFT_RADIUS_INDEX 15
+#define BORDER_TOP_LEFT_RADIUS_SHIFT 18
+#define BORDER_TOP_LEFT_RADIUS_MASK 0x40000
+static inline uint8_t get_border_top_left_radius_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[BORDER_TOP_LEFT_RADIUS_INDEX];
+	bits &= BORDER_TOP_LEFT_RADIUS_MASK;
+	bits >>= BORDER_TOP_LEFT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_border_top_left_radius(const css_computed_style
+		*style, lwc_string **string)
+{
+	uint32_t bits = style->i.bits[BORDER_TOP_LEFT_RADIUS_INDEX];
+	bits &= BORDER_TOP_LEFT_RADIUS_MASK;
+	bits >>= BORDER_TOP_LEFT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.border_top_left_radius;
+	
+	return (bits & 0x1);
+}
+#undef BORDER_TOP_LEFT_RADIUS_INDEX
+#undef BORDER_TOP_LEFT_RADIUS_SHIFT
+#undef BORDER_TOP_LEFT_RADIUS_MASK
+
+#define BORDER_TOP_RIGHT_RADIUS_INDEX 15
+#define BORDER_TOP_RIGHT_RADIUS_SHIFT 19
+#define BORDER_TOP_RIGHT_RADIUS_MASK 0x80000
+static inline uint8_t get_border_top_right_radius_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[BORDER_TOP_RIGHT_RADIUS_INDEX];
+	bits &= BORDER_TOP_RIGHT_RADIUS_MASK;
+	bits >>= BORDER_TOP_RIGHT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_border_top_right_radius(const css_computed_style
+		*style, lwc_string **string)
+{
+	uint32_t bits = style->i.bits[BORDER_TOP_RIGHT_RADIUS_INDEX];
+	bits &= BORDER_TOP_RIGHT_RADIUS_MASK;
+	bits >>= BORDER_TOP_RIGHT_RADIUS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.border_top_right_radius;
+	
+	return (bits & 0x1);
+}
+#undef BORDER_TOP_RIGHT_RADIUS_INDEX
+#undef BORDER_TOP_RIGHT_RADIUS_SHIFT
+#undef BORDER_TOP_RIGHT_RADIUS_MASK
+
+#define BORDER_TOP_STYLE_INDEX 12
+#define BORDER_TOP_STYLE_SHIFT 28
+#define BORDER_TOP_STYLE_MASK 0xf0000000
 static inline uint8_t get_border_top_style_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BORDER_TOP_STYLE_INDEX];
@@ -638,9 +754,9 @@ static inline uint8_t get_border_top_width(const css_computed_style *style,
 #undef BORDER_TOP_WIDTH_SHIFT
 #undef BORDER_TOP_WIDTH_MASK
 
-#define BOTTOM_INDEX 3
-#define BOTTOM_SHIFT 11
-#define BOTTOM_MASK 0x3f800
+#define BOTTOM_INDEX 7
+#define BOTTOM_SHIFT 4
+#define BOTTOM_MASK 0x7f0
 static inline uint8_t get_bottom_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BOTTOM_INDEX];
@@ -669,9 +785,37 @@ static inline uint8_t get_bottom(const css_computed_style *style, css_fixed
 #undef BOTTOM_SHIFT
 #undef BOTTOM_MASK
 
-#define BOX_SIZING_INDEX 11
-#define BOX_SIZING_SHIFT 10
-#define BOX_SIZING_MASK 0xc00
+#define BOX_SHADOW_INDEX 15
+#define BOX_SHADOW_SHIFT 20
+#define BOX_SHADOW_MASK 0x100000
+static inline uint8_t get_box_shadow_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[BOX_SHADOW_INDEX];
+	bits &= BOX_SHADOW_MASK;
+	bits >>= BOX_SHADOW_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_box_shadow(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[BOX_SHADOW_INDEX];
+	bits &= BOX_SHADOW_MASK;
+	bits >>= BOX_SHADOW_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.box_shadow;
+	
+	return (bits & 0x1);
+}
+#undef BOX_SHADOW_INDEX
+#undef BOX_SHADOW_SHIFT
+#undef BOX_SHADOW_MASK
+
+#define BOX_SIZING_INDEX 14
+#define BOX_SIZING_SHIFT 22
+#define BOX_SIZING_MASK 0xc00000
 static inline uint8_t get_box_sizing_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BOX_SIZING_INDEX];
@@ -695,9 +839,9 @@ static inline uint8_t get_box_sizing(const css_computed_style *style)
 #undef BOX_SIZING_SHIFT
 #undef BOX_SIZING_MASK
 
-#define BREAK_AFTER_INDEX 9
-#define BREAK_AFTER_SHIFT 15
-#define BREAK_AFTER_MASK 0x78000
+#define BREAK_AFTER_INDEX 11
+#define BREAK_AFTER_SHIFT 1
+#define BREAK_AFTER_MASK 0x1e
 static inline uint8_t get_break_after_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BREAK_AFTER_INDEX];
@@ -721,9 +865,9 @@ static inline uint8_t get_break_after(const css_computed_style *style)
 #undef BREAK_AFTER_SHIFT
 #undef BREAK_AFTER_MASK
 
-#define BREAK_BEFORE_INDEX 9
-#define BREAK_BEFORE_SHIFT 19
-#define BREAK_BEFORE_MASK 0x780000
+#define BREAK_BEFORE_INDEX 11
+#define BREAK_BEFORE_SHIFT 5
+#define BREAK_BEFORE_MASK 0x1e0
 static inline uint8_t get_break_before_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BREAK_BEFORE_INDEX];
@@ -747,9 +891,9 @@ static inline uint8_t get_break_before(const css_computed_style *style)
 #undef BREAK_BEFORE_SHIFT
 #undef BREAK_BEFORE_MASK
 
-#define BREAK_INSIDE_INDEX 9
-#define BREAK_INSIDE_SHIFT 23
-#define BREAK_INSIDE_MASK 0x7800000
+#define BREAK_INSIDE_INDEX 11
+#define BREAK_INSIDE_SHIFT 9
+#define BREAK_INSIDE_MASK 0x1e00
 static inline uint8_t get_break_inside_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[BREAK_INSIDE_INDEX];
@@ -773,9 +917,9 @@ static inline uint8_t get_break_inside(const css_computed_style *style)
 #undef BREAK_INSIDE_SHIFT
 #undef BREAK_INSIDE_MASK
 
-#define CAPTION_SIDE_INDEX 11
-#define CAPTION_SIDE_SHIFT 12
-#define CAPTION_SIDE_MASK 0x3000
+#define CAPTION_SIDE_INDEX 14
+#define CAPTION_SIDE_SHIFT 24
+#define CAPTION_SIDE_MASK 0x3000000
 static inline uint8_t get_caption_side_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[CAPTION_SIDE_INDEX];
@@ -799,9 +943,9 @@ static inline uint8_t get_caption_side(const css_computed_style *style)
 #undef CAPTION_SIDE_SHIFT
 #undef CAPTION_SIDE_MASK
 
-#define CLEAR_INDEX 13
-#define CLEAR_SHIFT 1
-#define CLEAR_MASK 0xe
+#define CLEAR_INDEX 9
+#define CLEAR_SHIFT 11
+#define CLEAR_MASK 0x3800
 static inline uint8_t get_clear_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[CLEAR_INDEX];
@@ -877,9 +1021,9 @@ static inline uint8_t get_clip(
 #undef CLIP_SHIFT
 #undef CLIP_MASK
 
-#define COLOR_INDEX 14
-#define COLOR_SHIFT 17
-#define COLOR_MASK 0x20000
+#define COLOR_INDEX 15
+#define COLOR_SHIFT 21
+#define COLOR_MASK 0x200000
 static inline uint8_t get_color_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLOR_INDEX];
@@ -905,9 +1049,9 @@ static inline uint8_t get_color(const css_computed_style *style, css_color
 #undef COLOR_SHIFT
 #undef COLOR_MASK
 
-#define COLUMN_COUNT_INDEX 11
-#define COLUMN_COUNT_SHIFT 14
-#define COLUMN_COUNT_MASK 0xc000
+#define COLUMN_COUNT_INDEX 14
+#define COLUMN_COUNT_SHIFT 26
+#define COLUMN_COUNT_MASK 0xc000000
 static inline uint8_t get_column_count_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLUMN_COUNT_INDEX];
@@ -933,9 +1077,9 @@ static inline uint8_t get_column_count(const css_computed_style *style, int32_t
 #undef COLUMN_COUNT_SHIFT
 #undef COLUMN_COUNT_MASK
 
-#define COLUMN_FILL_INDEX 11
-#define COLUMN_FILL_SHIFT 16
-#define COLUMN_FILL_MASK 0x30000
+#define COLUMN_FILL_INDEX 14
+#define COLUMN_FILL_SHIFT 28
+#define COLUMN_FILL_MASK 0x30000000
 static inline uint8_t get_column_fill_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLUMN_FILL_INDEX];
@@ -959,9 +1103,9 @@ static inline uint8_t get_column_fill(const css_computed_style *style)
 #undef COLUMN_FILL_SHIFT
 #undef COLUMN_FILL_MASK
 
-#define COLUMN_GAP_INDEX 3
-#define COLUMN_GAP_SHIFT 18
-#define COLUMN_GAP_MASK 0x1fc0000
+#define COLUMN_GAP_INDEX 7
+#define COLUMN_GAP_SHIFT 11
+#define COLUMN_GAP_MASK 0x3f800
 static inline uint8_t get_column_gap_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLUMN_GAP_INDEX];
@@ -990,9 +1134,9 @@ static inline uint8_t get_column_gap(const css_computed_style *style, css_fixed
 #undef COLUMN_GAP_SHIFT
 #undef COLUMN_GAP_MASK
 
-#define COLUMN_RULE_COLOR_INDEX 11
-#define COLUMN_RULE_COLOR_SHIFT 18
-#define COLUMN_RULE_COLOR_MASK 0xc0000
+#define COLUMN_RULE_COLOR_INDEX 14
+#define COLUMN_RULE_COLOR_SHIFT 30
+#define COLUMN_RULE_COLOR_MASK 0xc0000000
 static inline uint8_t get_column_rule_color_bits(const css_computed_style
 		*style)
 {
@@ -1019,9 +1163,9 @@ static inline uint8_t get_column_rule_color(const css_computed_style *style,
 #undef COLUMN_RULE_COLOR_SHIFT
 #undef COLUMN_RULE_COLOR_MASK
 
-#define COLUMN_RULE_STYLE_INDEX 7
-#define COLUMN_RULE_STYLE_SHIFT 0
-#define COLUMN_RULE_STYLE_MASK 0xf
+#define COLUMN_RULE_STYLE_INDEX 11
+#define COLUMN_RULE_STYLE_SHIFT 13
+#define COLUMN_RULE_STYLE_MASK 0x1e000
 static inline uint8_t get_column_rule_style_bits(const css_computed_style
 		*style)
 {
@@ -1078,9 +1222,9 @@ static inline uint8_t get_column_rule_width(const css_computed_style *style,
 #undef COLUMN_RULE_WIDTH_SHIFT
 #undef COLUMN_RULE_WIDTH_MASK
 
-#define COLUMN_SPAN_INDEX 11
-#define COLUMN_SPAN_SHIFT 20
-#define COLUMN_SPAN_MASK 0x300000
+#define COLUMN_SPAN_INDEX 13
+#define COLUMN_SPAN_SHIFT 1
+#define COLUMN_SPAN_MASK 0x6
 static inline uint8_t get_column_span_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLUMN_SPAN_INDEX];
@@ -1104,9 +1248,9 @@ static inline uint8_t get_column_span(const css_computed_style *style)
 #undef COLUMN_SPAN_SHIFT
 #undef COLUMN_SPAN_MASK
 
-#define COLUMN_WIDTH_INDEX 3
-#define COLUMN_WIDTH_SHIFT 25
-#define COLUMN_WIDTH_MASK 0xfe000000
+#define COLUMN_WIDTH_INDEX 7
+#define COLUMN_WIDTH_SHIFT 18
+#define COLUMN_WIDTH_MASK 0x1fc0000
 static inline uint8_t get_column_width_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COLUMN_WIDTH_INDEX];
@@ -1135,9 +1279,9 @@ static inline uint8_t get_column_width(const css_computed_style *style,
 #undef COLUMN_WIDTH_SHIFT
 #undef COLUMN_WIDTH_MASK
 
-#define CONTENT_INDEX 11
-#define CONTENT_SHIFT 22
-#define CONTENT_MASK 0xc00000
+#define CONTENT_INDEX 13
+#define CONTENT_SHIFT 3
+#define CONTENT_MASK 0x18
 static inline uint8_t get_content_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[CONTENT_INDEX];
@@ -1165,9 +1309,9 @@ static inline uint8_t get_content(const css_computed_style *style, const
 #undef CONTENT_SHIFT
 #undef CONTENT_MASK
 
-#define COUNTER_INCREMENT_INDEX 14
-#define COUNTER_INCREMENT_SHIFT 18
-#define COUNTER_INCREMENT_MASK 0x40000
+#define COUNTER_INCREMENT_INDEX 15
+#define COUNTER_INCREMENT_SHIFT 22
+#define COUNTER_INCREMENT_MASK 0x400000
 static inline uint8_t get_counter_increment_bits(const css_computed_style
 		*style)
 {
@@ -1194,9 +1338,9 @@ static inline uint8_t get_counter_increment(const css_computed_style *style,
 #undef COUNTER_INCREMENT_SHIFT
 #undef COUNTER_INCREMENT_MASK
 
-#define COUNTER_RESET_INDEX 14
-#define COUNTER_RESET_SHIFT 19
-#define COUNTER_RESET_MASK 0x80000
+#define COUNTER_RESET_INDEX 15
+#define COUNTER_RESET_SHIFT 23
+#define COUNTER_RESET_MASK 0x800000
 static inline uint8_t get_counter_reset_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[COUNTER_RESET_INDEX];
@@ -1222,9 +1366,9 @@ static inline uint8_t get_counter_reset(const css_computed_style *style, const
 #undef COUNTER_RESET_SHIFT
 #undef COUNTER_RESET_MASK
 
-#define CURSOR_INDEX 9
-#define CURSOR_SHIFT 27
-#define CURSOR_MASK 0xf8000000
+#define CURSOR_INDEX 11
+#define CURSOR_SHIFT 17
+#define CURSOR_MASK 0x3e0000
 static inline uint8_t get_cursor_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[CURSOR_INDEX];
@@ -1250,9 +1394,9 @@ static inline uint8_t get_cursor(const css_computed_style *style, lwc_string
 #undef CURSOR_SHIFT
 #undef CURSOR_MASK
 
-#define DIRECTION_INDEX 11
-#define DIRECTION_SHIFT 24
-#define DIRECTION_MASK 0x3000000
+#define DIRECTION_INDEX 13
+#define DIRECTION_SHIFT 5
+#define DIRECTION_MASK 0x60
 static inline uint8_t get_direction_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[DIRECTION_INDEX];
@@ -1276,9 +1420,9 @@ static inline uint8_t get_direction(const css_computed_style *style)
 #undef DIRECTION_SHIFT
 #undef DIRECTION_MASK
 
-#define DISPLAY_INDEX 8
-#define DISPLAY_SHIFT 3
-#define DISPLAY_MASK 0xf8
+#define DISPLAY_INDEX 11
+#define DISPLAY_SHIFT 22
+#define DISPLAY_MASK 0x7c00000
 static inline uint8_t get_display_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[DISPLAY_INDEX];
@@ -1302,9 +1446,9 @@ static inline uint8_t get_display(const css_computed_style *style)
 #undef DISPLAY_SHIFT
 #undef DISPLAY_MASK
 
-#define EMPTY_CELLS_INDEX 11
-#define EMPTY_CELLS_SHIFT 26
-#define EMPTY_CELLS_MASK 0xc000000
+#define EMPTY_CELLS_INDEX 13
+#define EMPTY_CELLS_SHIFT 7
+#define EMPTY_CELLS_MASK 0x180
 static inline uint8_t get_empty_cells_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[EMPTY_CELLS_INDEX];
@@ -1328,9 +1472,9 @@ static inline uint8_t get_empty_cells(const css_computed_style *style)
 #undef EMPTY_CELLS_SHIFT
 #undef EMPTY_CELLS_MASK
 
-#define FILL_OPACITY_INDEX 14
-#define FILL_OPACITY_SHIFT 20
-#define FILL_OPACITY_MASK 0x100000
+#define FILL_OPACITY_INDEX 15
+#define FILL_OPACITY_SHIFT 24
+#define FILL_OPACITY_MASK 0x1000000
 static inline uint8_t get_fill_opacity_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FILL_OPACITY_INDEX];
@@ -1359,8 +1503,8 @@ static inline uint8_t get_fill_opacity(const css_computed_style *style,
 #undef FILL_OPACITY_MASK
 
 #define FLEX_BASIS_INDEX 7
-#define FLEX_BASIS_SHIFT 4
-#define FLEX_BASIS_MASK 0x7f0
+#define FLEX_BASIS_SHIFT 25
+#define FLEX_BASIS_MASK 0xfe000000
 static inline uint8_t get_flex_basis_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLEX_BASIS_INDEX];
@@ -1389,9 +1533,9 @@ static inline uint8_t get_flex_basis(const css_computed_style *style, css_fixed
 #undef FLEX_BASIS_SHIFT
 #undef FLEX_BASIS_MASK
 
-#define FLEX_DIRECTION_INDEX 13
-#define FLEX_DIRECTION_SHIFT 4
-#define FLEX_DIRECTION_MASK 0x70
+#define FLEX_DIRECTION_INDEX 9
+#define FLEX_DIRECTION_SHIFT 14
+#define FLEX_DIRECTION_MASK 0x1c000
 static inline uint8_t get_flex_direction_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLEX_DIRECTION_INDEX];
@@ -1415,9 +1559,9 @@ static inline uint8_t get_flex_direction(const css_computed_style *style)
 #undef FLEX_DIRECTION_SHIFT
 #undef FLEX_DIRECTION_MASK
 
-#define FLEX_GROW_INDEX 14
-#define FLEX_GROW_SHIFT 21
-#define FLEX_GROW_MASK 0x200000
+#define FLEX_GROW_INDEX 15
+#define FLEX_GROW_SHIFT 25
+#define FLEX_GROW_MASK 0x2000000
 static inline uint8_t get_flex_grow_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLEX_GROW_INDEX];
@@ -1445,9 +1589,9 @@ static inline uint8_t get_flex_grow(const css_computed_style *style, css_fixed
 #undef FLEX_GROW_SHIFT
 #undef FLEX_GROW_MASK
 
-#define FLEX_SHRINK_INDEX 14
-#define FLEX_SHRINK_SHIFT 22
-#define FLEX_SHRINK_MASK 0x400000
+#define FLEX_SHRINK_INDEX 15
+#define FLEX_SHRINK_SHIFT 26
+#define FLEX_SHRINK_MASK 0x4000000
 static inline uint8_t get_flex_shrink_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLEX_SHRINK_INDEX];
@@ -1475,9 +1619,9 @@ static inline uint8_t get_flex_shrink(const css_computed_style *style,
 #undef FLEX_SHRINK_SHIFT
 #undef FLEX_SHRINK_MASK
 
-#define FLEX_WRAP_INDEX 11
-#define FLEX_WRAP_SHIFT 28
-#define FLEX_WRAP_MASK 0x30000000
+#define FLEX_WRAP_INDEX 13
+#define FLEX_WRAP_SHIFT 9
+#define FLEX_WRAP_MASK 0x600
 static inline uint8_t get_flex_wrap_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLEX_WRAP_INDEX];
@@ -1501,9 +1645,9 @@ static inline uint8_t get_flex_wrap(const css_computed_style *style)
 #undef FLEX_WRAP_SHIFT
 #undef FLEX_WRAP_MASK
 
-#define FLOAT_INDEX 11
-#define FLOAT_SHIFT 30
-#define FLOAT_MASK 0xc0000000
+#define FLOAT_INDEX 13
+#define FLOAT_SHIFT 11
+#define FLOAT_MASK 0x1800
 static inline uint8_t get_float_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FLOAT_INDEX];
@@ -1527,9 +1671,9 @@ static inline uint8_t get_float(const css_computed_style *style)
 #undef FLOAT_SHIFT
 #undef FLOAT_MASK
 
-#define FONT_FAMILY_INDEX 13
-#define FONT_FAMILY_SHIFT 7
-#define FONT_FAMILY_MASK 0x380
+#define FONT_FAMILY_INDEX 9
+#define FONT_FAMILY_SHIFT 17
+#define FONT_FAMILY_MASK 0xe0000
 static inline uint8_t get_font_family_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FONT_FAMILY_INDEX];
@@ -1586,9 +1730,9 @@ static inline uint8_t get_font_size(const css_computed_style *style, css_fixed
 #undef FONT_SIZE_SHIFT
 #undef FONT_SIZE_MASK
 
-#define FONT_STYLE_INDEX 10
-#define FONT_STYLE_SHIFT 0
-#define FONT_STYLE_MASK 0x3
+#define FONT_STYLE_INDEX 13
+#define FONT_STYLE_SHIFT 13
+#define FONT_STYLE_MASK 0x6000
 static inline uint8_t get_font_style_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FONT_STYLE_INDEX];
@@ -1612,9 +1756,9 @@ static inline uint8_t get_font_style(const css_computed_style *style)
 #undef FONT_STYLE_SHIFT
 #undef FONT_STYLE_MASK
 
-#define FONT_VARIANT_INDEX 10
-#define FONT_VARIANT_SHIFT 2
-#define FONT_VARIANT_MASK 0xc
+#define FONT_VARIANT_INDEX 13
+#define FONT_VARIANT_SHIFT 15
+#define FONT_VARIANT_MASK 0x18000
 static inline uint8_t get_font_variant_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[FONT_VARIANT_INDEX];
@@ -1638,7 +1782,7 @@ static inline uint8_t get_font_variant(const css_computed_style *style)
 #undef FONT_VARIANT_SHIFT
 #undef FONT_VARIANT_MASK
 
-#define FONT_WEIGHT_INDEX 6
+#define FONT_WEIGHT_INDEX 7
 #define FONT_WEIGHT_SHIFT 0
 #define FONT_WEIGHT_MASK 0xf
 static inline uint8_t get_font_weight_bits(const css_computed_style *style)
@@ -1664,9 +1808,292 @@ static inline uint8_t get_font_weight(const css_computed_style *style)
 #undef FONT_WEIGHT_SHIFT
 #undef FONT_WEIGHT_MASK
 
-#define HEIGHT_INDEX 7
-#define HEIGHT_SHIFT 11
-#define HEIGHT_MASK 0x3f800
+#define GRID_AUTO_COLUMNS_INDEX 15
+#define GRID_AUTO_COLUMNS_SHIFT 27
+#define GRID_AUTO_COLUMNS_MASK 0x8000000
+static inline uint8_t get_grid_auto_columns_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_COLUMNS_INDEX];
+	bits &= GRID_AUTO_COLUMNS_MASK;
+	bits >>= GRID_AUTO_COLUMNS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_auto_columns(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_COLUMNS_INDEX];
+	bits &= GRID_AUTO_COLUMNS_MASK;
+	bits >>= GRID_AUTO_COLUMNS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_auto_columns;
+	
+	return (bits & 0x1);
+}
+#undef GRID_AUTO_COLUMNS_INDEX
+#undef GRID_AUTO_COLUMNS_SHIFT
+#undef GRID_AUTO_COLUMNS_MASK
+
+#define GRID_AUTO_FLOW_INDEX 9
+#define GRID_AUTO_FLOW_SHIFT 20
+#define GRID_AUTO_FLOW_MASK 0x700000
+static inline uint8_t get_grid_auto_flow_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_FLOW_INDEX];
+	bits &= GRID_AUTO_FLOW_MASK;
+	bits >>= GRID_AUTO_FLOW_SHIFT;
+	
+	/* 3bits: ttt : type */
+	return (bits & 0x7);
+}
+static inline uint8_t get_grid_auto_flow(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_FLOW_INDEX];
+	bits &= GRID_AUTO_FLOW_MASK;
+	bits >>= GRID_AUTO_FLOW_SHIFT;
+	
+	/* 3bits: ttt : type */
+	
+	return (bits & 0x7);
+}
+#undef GRID_AUTO_FLOW_INDEX
+#undef GRID_AUTO_FLOW_SHIFT
+#undef GRID_AUTO_FLOW_MASK
+
+#define GRID_AUTO_ROWS_INDEX 15
+#define GRID_AUTO_ROWS_SHIFT 28
+#define GRID_AUTO_ROWS_MASK 0x10000000
+static inline uint8_t get_grid_auto_rows_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_ROWS_INDEX];
+	bits &= GRID_AUTO_ROWS_MASK;
+	bits >>= GRID_AUTO_ROWS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_auto_rows(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_AUTO_ROWS_INDEX];
+	bits &= GRID_AUTO_ROWS_MASK;
+	bits >>= GRID_AUTO_ROWS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_auto_rows;
+	
+	return (bits & 0x1);
+}
+#undef GRID_AUTO_ROWS_INDEX
+#undef GRID_AUTO_ROWS_SHIFT
+#undef GRID_AUTO_ROWS_MASK
+
+#define GRID_COLUMN_END_INDEX 15
+#define GRID_COLUMN_END_SHIFT 29
+#define GRID_COLUMN_END_MASK 0x20000000
+static inline uint8_t get_grid_column_end_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_COLUMN_END_INDEX];
+	bits &= GRID_COLUMN_END_MASK;
+	bits >>= GRID_COLUMN_END_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_column_end(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_COLUMN_END_INDEX];
+	bits &= GRID_COLUMN_END_MASK;
+	bits >>= GRID_COLUMN_END_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_column_end;
+	
+	return (bits & 0x1);
+}
+#undef GRID_COLUMN_END_INDEX
+#undef GRID_COLUMN_END_SHIFT
+#undef GRID_COLUMN_END_MASK
+
+#define GRID_COLUMN_START_INDEX 15
+#define GRID_COLUMN_START_SHIFT 30
+#define GRID_COLUMN_START_MASK 0x40000000
+static inline uint8_t get_grid_column_start_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[GRID_COLUMN_START_INDEX];
+	bits &= GRID_COLUMN_START_MASK;
+	bits >>= GRID_COLUMN_START_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_column_start(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_COLUMN_START_INDEX];
+	bits &= GRID_COLUMN_START_MASK;
+	bits >>= GRID_COLUMN_START_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_column_start;
+	
+	return (bits & 0x1);
+}
+#undef GRID_COLUMN_START_INDEX
+#undef GRID_COLUMN_START_SHIFT
+#undef GRID_COLUMN_START_MASK
+
+#define GRID_ROW_END_INDEX 15
+#define GRID_ROW_END_SHIFT 31
+#define GRID_ROW_END_MASK 0x80000000
+static inline uint8_t get_grid_row_end_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_ROW_END_INDEX];
+	bits &= GRID_ROW_END_MASK;
+	bits >>= GRID_ROW_END_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_row_end(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_ROW_END_INDEX];
+	bits &= GRID_ROW_END_MASK;
+	bits >>= GRID_ROW_END_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_row_end;
+	
+	return (bits & 0x1);
+}
+#undef GRID_ROW_END_INDEX
+#undef GRID_ROW_END_SHIFT
+#undef GRID_ROW_END_MASK
+
+#define GRID_ROW_START_INDEX 14
+#define GRID_ROW_START_SHIFT 0
+#define GRID_ROW_START_MASK 0x1
+static inline uint8_t get_grid_row_start_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[GRID_ROW_START_INDEX];
+	bits &= GRID_ROW_START_MASK;
+	bits >>= GRID_ROW_START_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_row_start(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_ROW_START_INDEX];
+	bits &= GRID_ROW_START_MASK;
+	bits >>= GRID_ROW_START_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_row_start;
+	
+	return (bits & 0x1);
+}
+#undef GRID_ROW_START_INDEX
+#undef GRID_ROW_START_SHIFT
+#undef GRID_ROW_START_MASK
+
+#define GRID_TEMPLATE_AREAS_INDEX 14
+#define GRID_TEMPLATE_AREAS_SHIFT 1
+#define GRID_TEMPLATE_AREAS_MASK 0x2
+static inline uint8_t get_grid_template_areas_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_AREAS_INDEX];
+	bits &= GRID_TEMPLATE_AREAS_MASK;
+	bits >>= GRID_TEMPLATE_AREAS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_template_areas(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_AREAS_INDEX];
+	bits &= GRID_TEMPLATE_AREAS_MASK;
+	bits >>= GRID_TEMPLATE_AREAS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_template_areas;
+	
+	return (bits & 0x1);
+}
+#undef GRID_TEMPLATE_AREAS_INDEX
+#undef GRID_TEMPLATE_AREAS_SHIFT
+#undef GRID_TEMPLATE_AREAS_MASK
+
+#define GRID_TEMPLATE_COLUMNS_INDEX 14
+#define GRID_TEMPLATE_COLUMNS_SHIFT 2
+#define GRID_TEMPLATE_COLUMNS_MASK 0x4
+static inline uint8_t get_grid_template_columns_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_COLUMNS_INDEX];
+	bits &= GRID_TEMPLATE_COLUMNS_MASK;
+	bits >>= GRID_TEMPLATE_COLUMNS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_template_columns(const css_computed_style
+		*style, lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_COLUMNS_INDEX];
+	bits &= GRID_TEMPLATE_COLUMNS_MASK;
+	bits >>= GRID_TEMPLATE_COLUMNS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_template_columns;
+	
+	return (bits & 0x1);
+}
+#undef GRID_TEMPLATE_COLUMNS_INDEX
+#undef GRID_TEMPLATE_COLUMNS_SHIFT
+#undef GRID_TEMPLATE_COLUMNS_MASK
+
+#define GRID_TEMPLATE_ROWS_INDEX 14
+#define GRID_TEMPLATE_ROWS_SHIFT 3
+#define GRID_TEMPLATE_ROWS_MASK 0x8
+static inline uint8_t get_grid_template_rows_bits(const css_computed_style
+		*style)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_ROWS_INDEX];
+	bits &= GRID_TEMPLATE_ROWS_MASK;
+	bits >>= GRID_TEMPLATE_ROWS_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_grid_template_rows(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[GRID_TEMPLATE_ROWS_INDEX];
+	bits &= GRID_TEMPLATE_ROWS_MASK;
+	bits >>= GRID_TEMPLATE_ROWS_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.grid_template_rows;
+	
+	return (bits & 0x1);
+}
+#undef GRID_TEMPLATE_ROWS_INDEX
+#undef GRID_TEMPLATE_ROWS_SHIFT
+#undef GRID_TEMPLATE_ROWS_MASK
+
+#define HEIGHT_INDEX 6
+#define HEIGHT_SHIFT 4
+#define HEIGHT_MASK 0x7f0
 static inline uint8_t get_height_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[HEIGHT_INDEX];
@@ -1695,9 +2122,9 @@ static inline uint8_t get_height(const css_computed_style *style, css_fixed
 #undef HEIGHT_SHIFT
 #undef HEIGHT_MASK
 
-#define JUSTIFY_CONTENT_INDEX 13
-#define JUSTIFY_CONTENT_SHIFT 10
-#define JUSTIFY_CONTENT_MASK 0x1c00
+#define JUSTIFY_CONTENT_INDEX 9
+#define JUSTIFY_CONTENT_SHIFT 23
+#define JUSTIFY_CONTENT_MASK 0x3800000
 static inline uint8_t get_justify_content_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[JUSTIFY_CONTENT_INDEX];
@@ -1721,9 +2148,61 @@ static inline uint8_t get_justify_content(const css_computed_style *style)
 #undef JUSTIFY_CONTENT_SHIFT
 #undef JUSTIFY_CONTENT_MASK
 
-#define LEFT_INDEX 7
-#define LEFT_SHIFT 18
-#define LEFT_MASK 0x1fc0000
+#define JUSTIFY_ITEMS_INDEX 6
+#define JUSTIFY_ITEMS_SHIFT 0
+#define JUSTIFY_ITEMS_MASK 0xf
+static inline uint8_t get_justify_items_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[JUSTIFY_ITEMS_INDEX];
+	bits &= JUSTIFY_ITEMS_MASK;
+	bits >>= JUSTIFY_ITEMS_SHIFT;
+	
+	/* 4bits: tttt : type */
+	return (bits & 0xf);
+}
+static inline uint8_t get_justify_items(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[JUSTIFY_ITEMS_INDEX];
+	bits &= JUSTIFY_ITEMS_MASK;
+	bits >>= JUSTIFY_ITEMS_SHIFT;
+	
+	/* 4bits: tttt : type */
+	
+	return (bits & 0xf);
+}
+#undef JUSTIFY_ITEMS_INDEX
+#undef JUSTIFY_ITEMS_SHIFT
+#undef JUSTIFY_ITEMS_MASK
+
+#define JUSTIFY_SELF_INDEX 5
+#define JUSTIFY_SELF_SHIFT 0
+#define JUSTIFY_SELF_MASK 0xf
+static inline uint8_t get_justify_self_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[JUSTIFY_SELF_INDEX];
+	bits &= JUSTIFY_SELF_MASK;
+	bits >>= JUSTIFY_SELF_SHIFT;
+	
+	/* 4bits: tttt : type */
+	return (bits & 0xf);
+}
+static inline uint8_t get_justify_self(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[JUSTIFY_SELF_INDEX];
+	bits &= JUSTIFY_SELF_MASK;
+	bits >>= JUSTIFY_SELF_SHIFT;
+	
+	/* 4bits: tttt : type */
+	
+	return (bits & 0xf);
+}
+#undef JUSTIFY_SELF_INDEX
+#undef JUSTIFY_SELF_SHIFT
+#undef JUSTIFY_SELF_MASK
+
+#define LEFT_INDEX 6
+#define LEFT_SHIFT 11
+#define LEFT_MASK 0x3f800
 static inline uint8_t get_left_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[LEFT_INDEX];
@@ -1752,9 +2231,9 @@ static inline uint8_t get_left(const css_computed_style *style, css_fixed
 #undef LEFT_SHIFT
 #undef LEFT_MASK
 
-#define LETTER_SPACING_INDEX 7
-#define LETTER_SPACING_SHIFT 25
-#define LETTER_SPACING_MASK 0xfe000000
+#define LETTER_SPACING_INDEX 6
+#define LETTER_SPACING_SHIFT 18
+#define LETTER_SPACING_MASK 0x1fc0000
 static inline uint8_t get_letter_spacing_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[LETTER_SPACING_INDEX];
@@ -1784,8 +2263,8 @@ static inline uint8_t get_letter_spacing(const css_computed_style *style,
 #undef LETTER_SPACING_MASK
 
 #define LINE_HEIGHT_INDEX 6
-#define LINE_HEIGHT_SHIFT 4
-#define LINE_HEIGHT_MASK 0x7f0
+#define LINE_HEIGHT_SHIFT 25
+#define LINE_HEIGHT_MASK 0xfe000000
 static inline uint8_t get_line_height_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[LINE_HEIGHT_INDEX];
@@ -1820,8 +2299,8 @@ static inline uint8_t get_line_height(
 #undef LINE_HEIGHT_MASK
 
 #define LIST_STYLE_IMAGE_INDEX 14
-#define LIST_STYLE_IMAGE_SHIFT 23
-#define LIST_STYLE_IMAGE_MASK 0x800000
+#define LIST_STYLE_IMAGE_SHIFT 4
+#define LIST_STYLE_IMAGE_MASK 0x10
 static inline uint8_t get_list_style_image_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[LIST_STYLE_IMAGE_INDEX];
@@ -1847,9 +2326,9 @@ static inline uint8_t get_list_style_image(const css_computed_style *style,
 #undef LIST_STYLE_IMAGE_SHIFT
 #undef LIST_STYLE_IMAGE_MASK
 
-#define LIST_STYLE_POSITION_INDEX 10
-#define LIST_STYLE_POSITION_SHIFT 4
-#define LIST_STYLE_POSITION_MASK 0x30
+#define LIST_STYLE_POSITION_INDEX 13
+#define LIST_STYLE_POSITION_SHIFT 17
+#define LIST_STYLE_POSITION_MASK 0x60000
 static inline uint8_t get_list_style_position_bits(const css_computed_style
 		*style)
 {
@@ -1875,8 +2354,8 @@ static inline uint8_t get_list_style_position(const css_computed_style *style)
 #undef LIST_STYLE_POSITION_MASK
 
 #define LIST_STYLE_TYPE_INDEX 8
-#define LIST_STYLE_TYPE_SHIFT 8
-#define LIST_STYLE_TYPE_MASK 0x3f00
+#define LIST_STYLE_TYPE_SHIFT 2
+#define LIST_STYLE_TYPE_MASK 0xfc
 static inline uint8_t get_list_style_type_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[LIST_STYLE_TYPE_INDEX];
@@ -1900,9 +2379,9 @@ static inline uint8_t get_list_style_type(const css_computed_style *style)
 #undef LIST_STYLE_TYPE_SHIFT
 #undef LIST_STYLE_TYPE_MASK
 
-#define MARGIN_BOTTOM_INDEX 6
-#define MARGIN_BOTTOM_SHIFT 11
-#define MARGIN_BOTTOM_MASK 0x3f800
+#define MARGIN_BOTTOM_INDEX 5
+#define MARGIN_BOTTOM_SHIFT 4
+#define MARGIN_BOTTOM_MASK 0x7f0
 static inline uint8_t get_margin_bottom_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MARGIN_BOTTOM_INDEX];
@@ -1931,9 +2410,9 @@ static inline uint8_t get_margin_bottom(const css_computed_style *style,
 #undef MARGIN_BOTTOM_SHIFT
 #undef MARGIN_BOTTOM_MASK
 
-#define MARGIN_LEFT_INDEX 6
-#define MARGIN_LEFT_SHIFT 18
-#define MARGIN_LEFT_MASK 0x1fc0000
+#define MARGIN_LEFT_INDEX 5
+#define MARGIN_LEFT_SHIFT 11
+#define MARGIN_LEFT_MASK 0x3f800
 static inline uint8_t get_margin_left_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MARGIN_LEFT_INDEX];
@@ -1962,9 +2441,9 @@ static inline uint8_t get_margin_left(const css_computed_style *style,
 #undef MARGIN_LEFT_SHIFT
 #undef MARGIN_LEFT_MASK
 
-#define MARGIN_RIGHT_INDEX 6
-#define MARGIN_RIGHT_SHIFT 25
-#define MARGIN_RIGHT_MASK 0xfe000000
+#define MARGIN_RIGHT_INDEX 5
+#define MARGIN_RIGHT_SHIFT 18
+#define MARGIN_RIGHT_MASK 0x1fc0000
 static inline uint8_t get_margin_right_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MARGIN_RIGHT_INDEX];
@@ -1994,8 +2473,8 @@ static inline uint8_t get_margin_right(const css_computed_style *style,
 #undef MARGIN_RIGHT_MASK
 
 #define MARGIN_TOP_INDEX 5
-#define MARGIN_TOP_SHIFT 4
-#define MARGIN_TOP_MASK 0x7f0
+#define MARGIN_TOP_SHIFT 25
+#define MARGIN_TOP_MASK 0xfe000000
 static inline uint8_t get_margin_top_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MARGIN_TOP_INDEX];
@@ -2024,9 +2503,9 @@ static inline uint8_t get_margin_top(const css_computed_style *style, css_fixed
 #undef MARGIN_TOP_SHIFT
 #undef MARGIN_TOP_MASK
 
-#define MAX_HEIGHT_INDEX 5
-#define MAX_HEIGHT_SHIFT 11
-#define MAX_HEIGHT_MASK 0x3f800
+#define MAX_HEIGHT_INDEX 4
+#define MAX_HEIGHT_SHIFT 4
+#define MAX_HEIGHT_MASK 0x7f0
 static inline uint8_t get_max_height_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MAX_HEIGHT_INDEX];
@@ -2055,9 +2534,9 @@ static inline uint8_t get_max_height(const css_computed_style *style, css_fixed
 #undef MAX_HEIGHT_SHIFT
 #undef MAX_HEIGHT_MASK
 
-#define MAX_WIDTH_INDEX 5
-#define MAX_WIDTH_SHIFT 18
-#define MAX_WIDTH_MASK 0x1fc0000
+#define MAX_WIDTH_INDEX 4
+#define MAX_WIDTH_SHIFT 11
+#define MAX_WIDTH_MASK 0x3f800
 static inline uint8_t get_max_width_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MAX_WIDTH_INDEX];
@@ -2086,9 +2565,9 @@ static inline uint8_t get_max_width(const css_computed_style *style, css_fixed
 #undef MAX_WIDTH_SHIFT
 #undef MAX_WIDTH_MASK
 
-#define MIN_HEIGHT_INDEX 5
-#define MIN_HEIGHT_SHIFT 25
-#define MIN_HEIGHT_MASK 0xfe000000
+#define MIN_HEIGHT_INDEX 4
+#define MIN_HEIGHT_SHIFT 18
+#define MIN_HEIGHT_MASK 0x1fc0000
 static inline uint8_t get_min_height_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MIN_HEIGHT_INDEX];
@@ -2118,8 +2597,8 @@ static inline uint8_t get_min_height(const css_computed_style *style, css_fixed
 #undef MIN_HEIGHT_MASK
 
 #define MIN_WIDTH_INDEX 4
-#define MIN_WIDTH_SHIFT 4
-#define MIN_WIDTH_MASK 0x7f0
+#define MIN_WIDTH_SHIFT 25
+#define MIN_WIDTH_MASK 0xfe000000
 static inline uint8_t get_min_width_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[MIN_WIDTH_INDEX];
@@ -2149,8 +2628,8 @@ static inline uint8_t get_min_width(const css_computed_style *style, css_fixed
 #undef MIN_WIDTH_MASK
 
 #define OPACITY_INDEX 14
-#define OPACITY_SHIFT 24
-#define OPACITY_MASK 0x1000000
+#define OPACITY_SHIFT 5
+#define OPACITY_MASK 0x20
 static inline uint8_t get_opacity_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[OPACITY_INDEX];
@@ -2179,8 +2658,8 @@ static inline uint8_t get_opacity(const css_computed_style *style, css_fixed
 #undef OPACITY_MASK
 
 #define ORDER_INDEX 14
-#define ORDER_SHIFT 25
-#define ORDER_MASK 0x2000000
+#define ORDER_SHIFT 6
+#define ORDER_MASK 0x40
 static inline uint8_t get_order_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[ORDER_INDEX];
@@ -2209,8 +2688,8 @@ static inline uint8_t get_order(const css_computed_style *style, int32_t
 #undef ORDER_MASK
 
 #define ORPHANS_INDEX 14
-#define ORPHANS_SHIFT 26
-#define ORPHANS_MASK 0x4000000
+#define ORPHANS_SHIFT 7
+#define ORPHANS_MASK 0x80
 static inline uint8_t get_orphans_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[ORPHANS_INDEX];
@@ -2236,9 +2715,9 @@ static inline uint8_t get_orphans(const css_computed_style *style, int32_t
 #undef ORPHANS_SHIFT
 #undef ORPHANS_MASK
 
-#define OUTLINE_COLOR_INDEX 10
-#define OUTLINE_COLOR_SHIFT 6
-#define OUTLINE_COLOR_MASK 0xc0
+#define OUTLINE_COLOR_INDEX 13
+#define OUTLINE_COLOR_SHIFT 19
+#define OUTLINE_COLOR_MASK 0x180000
 static inline uint8_t get_outline_color_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[OUTLINE_COLOR_INDEX];
@@ -2266,7 +2745,7 @@ static inline uint8_t get_outline_color(const css_computed_style *style,
 #undef OUTLINE_COLOR_SHIFT
 #undef OUTLINE_COLOR_MASK
 
-#define OUTLINE_STYLE_INDEX 5
+#define OUTLINE_STYLE_INDEX 4
 #define OUTLINE_STYLE_SHIFT 0
 #define OUTLINE_STYLE_MASK 0xf
 static inline uint8_t get_outline_style_bits(const css_computed_style *style)
@@ -2323,9 +2802,9 @@ static inline uint8_t get_outline_width(const css_computed_style *style,
 #undef OUTLINE_WIDTH_SHIFT
 #undef OUTLINE_WIDTH_MASK
 
-#define OVERFLOW_X_INDEX 13
-#define OVERFLOW_X_SHIFT 13
-#define OVERFLOW_X_MASK 0xe000
+#define OVERFLOW_X_INDEX 9
+#define OVERFLOW_X_SHIFT 26
+#define OVERFLOW_X_MASK 0x1c000000
 static inline uint8_t get_overflow_x_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[OVERFLOW_X_INDEX];
@@ -2349,9 +2828,9 @@ static inline uint8_t get_overflow_x(const css_computed_style *style)
 #undef OVERFLOW_X_SHIFT
 #undef OVERFLOW_X_MASK
 
-#define OVERFLOW_Y_INDEX 13
-#define OVERFLOW_Y_SHIFT 16
-#define OVERFLOW_Y_MASK 0x70000
+#define OVERFLOW_Y_INDEX 9
+#define OVERFLOW_Y_SHIFT 29
+#define OVERFLOW_Y_MASK 0xe0000000
 static inline uint8_t get_overflow_y_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[OVERFLOW_Y_INDEX];
@@ -2376,8 +2855,8 @@ static inline uint8_t get_overflow_y(const css_computed_style *style)
 #undef OVERFLOW_Y_MASK
 
 #define PADDING_BOTTOM_INDEX 8
-#define PADDING_BOTTOM_SHIFT 14
-#define PADDING_BOTTOM_MASK 0xfc000
+#define PADDING_BOTTOM_SHIFT 8
+#define PADDING_BOTTOM_MASK 0x3f00
 static inline uint8_t get_padding_bottom_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[PADDING_BOTTOM_INDEX];
@@ -2407,8 +2886,8 @@ static inline uint8_t get_padding_bottom(const css_computed_style *style,
 #undef PADDING_BOTTOM_MASK
 
 #define PADDING_LEFT_INDEX 8
-#define PADDING_LEFT_SHIFT 20
-#define PADDING_LEFT_MASK 0x3f00000
+#define PADDING_LEFT_SHIFT 14
+#define PADDING_LEFT_MASK 0xfc000
 static inline uint8_t get_padding_left_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[PADDING_LEFT_INDEX];
@@ -2438,8 +2917,8 @@ static inline uint8_t get_padding_left(const css_computed_style *style,
 #undef PADDING_LEFT_MASK
 
 #define PADDING_RIGHT_INDEX 8
-#define PADDING_RIGHT_SHIFT 26
-#define PADDING_RIGHT_MASK 0xfc000000
+#define PADDING_RIGHT_SHIFT 20
+#define PADDING_RIGHT_MASK 0x3f00000
 static inline uint8_t get_padding_right_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[PADDING_RIGHT_INDEX];
@@ -2468,9 +2947,9 @@ static inline uint8_t get_padding_right(const css_computed_style *style,
 #undef PADDING_RIGHT_SHIFT
 #undef PADDING_RIGHT_MASK
 
-#define PADDING_TOP_INDEX 3
-#define PADDING_TOP_SHIFT 5
-#define PADDING_TOP_MASK 0x7e0
+#define PADDING_TOP_INDEX 8
+#define PADDING_TOP_SHIFT 26
+#define PADDING_TOP_MASK 0xfc000000
 static inline uint8_t get_padding_top_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[PADDING_TOP_INDEX];
@@ -2499,9 +2978,9 @@ static inline uint8_t get_padding_top(const css_computed_style *style,
 #undef PADDING_TOP_SHIFT
 #undef PADDING_TOP_MASK
 
-#define PAGE_BREAK_AFTER_INDEX 13
-#define PAGE_BREAK_AFTER_SHIFT 19
-#define PAGE_BREAK_AFTER_MASK 0x380000
+#define PAGE_BREAK_AFTER_INDEX 12
+#define PAGE_BREAK_AFTER_SHIFT 1
+#define PAGE_BREAK_AFTER_MASK 0xe
 static inline uint8_t get_page_break_after_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[PAGE_BREAK_AFTER_INDEX];
@@ -2525,9 +3004,9 @@ static inline uint8_t get_page_break_after(const css_computed_style *style)
 #undef PAGE_BREAK_AFTER_SHIFT
 #undef PAGE_BREAK_AFTER_MASK
 
-#define PAGE_BREAK_BEFORE_INDEX 13
-#define PAGE_BREAK_BEFORE_SHIFT 22
-#define PAGE_BREAK_BEFORE_MASK 0x1c00000
+#define PAGE_BREAK_BEFORE_INDEX 12
+#define PAGE_BREAK_BEFORE_SHIFT 4
+#define PAGE_BREAK_BEFORE_MASK 0x70
 static inline uint8_t get_page_break_before_bits(const css_computed_style
 		*style)
 {
@@ -2552,9 +3031,9 @@ static inline uint8_t get_page_break_before(const css_computed_style *style)
 #undef PAGE_BREAK_BEFORE_SHIFT
 #undef PAGE_BREAK_BEFORE_MASK
 
-#define PAGE_BREAK_INSIDE_INDEX 10
-#define PAGE_BREAK_INSIDE_SHIFT 8
-#define PAGE_BREAK_INSIDE_MASK 0x300
+#define PAGE_BREAK_INSIDE_INDEX 13
+#define PAGE_BREAK_INSIDE_SHIFT 21
+#define PAGE_BREAK_INSIDE_MASK 0x600000
 static inline uint8_t get_page_break_inside_bits(const css_computed_style
 		*style)
 {
@@ -2579,9 +3058,9 @@ static inline uint8_t get_page_break_inside(const css_computed_style *style)
 #undef PAGE_BREAK_INSIDE_SHIFT
 #undef PAGE_BREAK_INSIDE_MASK
 
-#define POSITION_INDEX 13
-#define POSITION_SHIFT 25
-#define POSITION_MASK 0xe000000
+#define POSITION_INDEX 12
+#define POSITION_SHIFT 7
+#define POSITION_MASK 0x380
 static inline uint8_t get_position_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[POSITION_INDEX];
@@ -2605,9 +3084,9 @@ static inline uint8_t get_position(const css_computed_style *style)
 #undef POSITION_SHIFT
 #undef POSITION_MASK
 
-#define QUOTES_INDEX 14
-#define QUOTES_SHIFT 27
-#define QUOTES_MASK 0x8000000
+#define QUOTES_INDEX 13
+#define QUOTES_SHIFT 0
+#define QUOTES_MASK 0x1
 static inline uint8_t get_quotes_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[QUOTES_INDEX];
@@ -2633,9 +3112,9 @@ static inline uint8_t get_quotes(const css_computed_style *style, lwc_string
 #undef QUOTES_SHIFT
 #undef QUOTES_MASK
 
-#define RIGHT_INDEX 4
-#define RIGHT_SHIFT 11
-#define RIGHT_MASK 0x3f800
+#define RIGHT_INDEX 3
+#define RIGHT_SHIFT 4
+#define RIGHT_MASK 0x7f0
 static inline uint8_t get_right_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[RIGHT_INDEX];
@@ -2664,7 +3143,38 @@ static inline uint8_t get_right(const css_computed_style *style, css_fixed
 #undef RIGHT_SHIFT
 #undef RIGHT_MASK
 
-#define STROKE_OPACITY_INDEX 13
+#define ROW_GAP_INDEX 3
+#define ROW_GAP_SHIFT 11
+#define ROW_GAP_MASK 0x3f800
+static inline uint8_t get_row_gap_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[ROW_GAP_INDEX];
+	bits &= ROW_GAP_MASK;
+	bits >>= ROW_GAP_SHIFT;
+	
+	/* 7bits: uuuuutt : unit | type */
+	return (bits & 0x3);
+}
+static inline uint8_t get_row_gap(const css_computed_style *style, css_fixed
+		*length, css_unit *unit)
+{
+	uint32_t bits = style->i.bits[ROW_GAP_INDEX];
+	bits &= ROW_GAP_MASK;
+	bits >>= ROW_GAP_SHIFT;
+	
+	/* 7bits: uuuuutt : unit | type */
+	if ((bits & 0x3) == CSS_ROW_GAP_SET) {
+		*length = style->i.row_gap;
+		*unit = bits >> 2;
+	}
+	
+	return (bits & 0x3);
+}
+#undef ROW_GAP_INDEX
+#undef ROW_GAP_SHIFT
+#undef ROW_GAP_MASK
+
+#define STROKE_OPACITY_INDEX 12
 #define STROKE_OPACITY_SHIFT 0
 #define STROKE_OPACITY_MASK 0x1
 static inline uint8_t get_stroke_opacity_bits(const css_computed_style *style)
@@ -2694,9 +3204,9 @@ static inline uint8_t get_stroke_opacity(const css_computed_style *style,
 #undef STROKE_OPACITY_SHIFT
 #undef STROKE_OPACITY_MASK
 
-#define TABLE_LAYOUT_INDEX 10
-#define TABLE_LAYOUT_SHIFT 10
-#define TABLE_LAYOUT_MASK 0xc00
+#define TABLE_LAYOUT_INDEX 13
+#define TABLE_LAYOUT_SHIFT 23
+#define TABLE_LAYOUT_MASK 0x1800000
 static inline uint8_t get_table_layout_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[TABLE_LAYOUT_INDEX];
@@ -2720,7 +3230,7 @@ static inline uint8_t get_table_layout(const css_computed_style *style)
 #undef TABLE_LAYOUT_SHIFT
 #undef TABLE_LAYOUT_MASK
 
-#define TEXT_ALIGN_INDEX 4
+#define TEXT_ALIGN_INDEX 3
 #define TEXT_ALIGN_SHIFT 0
 #define TEXT_ALIGN_MASK 0xf
 static inline uint8_t get_text_align_bits(const css_computed_style *style)
@@ -2746,9 +3256,9 @@ static inline uint8_t get_text_align(const css_computed_style *style)
 #undef TEXT_ALIGN_SHIFT
 #undef TEXT_ALIGN_MASK
 
-#define TEXT_DECORATION_INDEX 3
-#define TEXT_DECORATION_SHIFT 0
-#define TEXT_DECORATION_MASK 0x1f
+#define TEXT_DECORATION_INDEX 11
+#define TEXT_DECORATION_SHIFT 27
+#define TEXT_DECORATION_MASK 0xf8000000
 static inline uint8_t get_text_decoration_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[TEXT_DECORATION_INDEX];
@@ -2803,9 +3313,37 @@ static inline uint8_t get_text_indent(const css_computed_style *style,
 #undef TEXT_INDENT_SHIFT
 #undef TEXT_INDENT_MASK
 
-#define TEXT_TRANSFORM_INDEX 9
-#define TEXT_TRANSFORM_SHIFT 0
-#define TEXT_TRANSFORM_MASK 0x7
+#define TEXT_SHADOW_INDEX 11
+#define TEXT_SHADOW_SHIFT 0
+#define TEXT_SHADOW_MASK 0x1
+static inline uint8_t get_text_shadow_bits(const css_computed_style *style)
+{
+	uint32_t bits = style->i.bits[TEXT_SHADOW_INDEX];
+	bits &= TEXT_SHADOW_MASK;
+	bits >>= TEXT_SHADOW_SHIFT;
+	
+	/* 1bit: t : type */
+	return (bits & 0x1);
+}
+static inline uint8_t get_text_shadow(const css_computed_style *style,
+		lwc_string **string)
+{
+	uint32_t bits = style->i.bits[TEXT_SHADOW_INDEX];
+	bits &= TEXT_SHADOW_MASK;
+	bits >>= TEXT_SHADOW_SHIFT;
+	
+	/* 1bit: t : type */
+	*string = style->i.text_shadow;
+	
+	return (bits & 0x1);
+}
+#undef TEXT_SHADOW_INDEX
+#undef TEXT_SHADOW_SHIFT
+#undef TEXT_SHADOW_MASK
+
+#define TEXT_TRANSFORM_INDEX 12
+#define TEXT_TRANSFORM_SHIFT 10
+#define TEXT_TRANSFORM_MASK 0x1c00
 static inline uint8_t get_text_transform_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[TEXT_TRANSFORM_INDEX];
@@ -2829,7 +3367,7 @@ static inline uint8_t get_text_transform(const css_computed_style *style)
 #undef TEXT_TRANSFORM_SHIFT
 #undef TEXT_TRANSFORM_MASK
 
-#define TOP_INDEX 4
+#define TOP_INDEX 3
 #define TOP_SHIFT 18
 #define TOP_MASK 0x1fc0000
 static inline uint8_t get_top_bits(const css_computed_style *style)
@@ -2860,9 +3398,9 @@ static inline uint8_t get_top(const css_computed_style *style, css_fixed
 #undef TOP_SHIFT
 #undef TOP_MASK
 
-#define UNICODE_BIDI_INDEX 10
-#define UNICODE_BIDI_SHIFT 12
-#define UNICODE_BIDI_MASK 0x3000
+#define UNICODE_BIDI_INDEX 13
+#define UNICODE_BIDI_SHIFT 25
+#define UNICODE_BIDI_MASK 0x6000000
 static inline uint8_t get_unicode_bidi_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[UNICODE_BIDI_INDEX];
@@ -2886,7 +3424,7 @@ static inline uint8_t get_unicode_bidi(const css_computed_style *style)
 #undef UNICODE_BIDI_SHIFT
 #undef UNICODE_BIDI_MASK
 
-#define VERTICAL_ALIGN_INDEX 12
+#define VERTICAL_ALIGN_INDEX 10
 #define VERTICAL_ALIGN_SHIFT 1
 #define VERTICAL_ALIGN_MASK 0x3fe
 static inline uint8_t get_vertical_align_bits(const css_computed_style *style)
@@ -2917,9 +3455,9 @@ static inline uint8_t get_vertical_align(const css_computed_style *style,
 #undef VERTICAL_ALIGN_SHIFT
 #undef VERTICAL_ALIGN_MASK
 
-#define VISIBILITY_INDEX 10
-#define VISIBILITY_SHIFT 14
-#define VISIBILITY_MASK 0xc000
+#define VISIBILITY_INDEX 13
+#define VISIBILITY_SHIFT 27
+#define VISIBILITY_MASK 0x18000000
 static inline uint8_t get_visibility_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[VISIBILITY_INDEX];
@@ -2943,9 +3481,9 @@ static inline uint8_t get_visibility(const css_computed_style *style)
 #undef VISIBILITY_SHIFT
 #undef VISIBILITY_MASK
 
-#define WHITE_SPACE_INDEX 8
-#define WHITE_SPACE_SHIFT 0
-#define WHITE_SPACE_MASK 0x7
+#define WHITE_SPACE_INDEX 12
+#define WHITE_SPACE_SHIFT 13
+#define WHITE_SPACE_MASK 0xe000
 static inline uint8_t get_white_space_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[WHITE_SPACE_INDEX];
@@ -2969,7 +3507,7 @@ static inline uint8_t get_white_space(const css_computed_style *style)
 #undef WHITE_SPACE_SHIFT
 #undef WHITE_SPACE_MASK
 
-#define WIDOWS_INDEX 12
+#define WIDOWS_INDEX 10
 #define WIDOWS_SHIFT 0
 #define WIDOWS_MASK 0x1
 static inline uint8_t get_widows_bits(const css_computed_style *style)
@@ -2997,7 +3535,7 @@ static inline uint8_t get_widows(const css_computed_style *style, int32_t
 #undef WIDOWS_SHIFT
 #undef WIDOWS_MASK
 
-#define WIDTH_INDEX 4
+#define WIDTH_INDEX 3
 #define WIDTH_SHIFT 25
 #define WIDTH_MASK 0xfe000000
 static inline uint8_t get_width_bits(const css_computed_style *style)
@@ -3059,9 +3597,9 @@ static inline uint8_t get_word_spacing(const css_computed_style *style,
 #undef WORD_SPACING_SHIFT
 #undef WORD_SPACING_MASK
 
-#define WRITING_MODE_INDEX 10
-#define WRITING_MODE_SHIFT 16
-#define WRITING_MODE_MASK 0x30000
+#define WRITING_MODE_INDEX 9
+#define WRITING_MODE_SHIFT 0
+#define WRITING_MODE_MASK 0x3
 static inline uint8_t get_writing_mode_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[WRITING_MODE_INDEX];
@@ -3085,9 +3623,9 @@ static inline uint8_t get_writing_mode(const css_computed_style *style)
 #undef WRITING_MODE_SHIFT
 #undef WRITING_MODE_MASK
 
-#define Z_INDEX_INDEX 10
-#define Z_INDEX_SHIFT 18
-#define Z_INDEX_MASK 0xc0000
+#define Z_INDEX_INDEX 8
+#define Z_INDEX_SHIFT 0
+#define Z_INDEX_MASK 0x3
 static inline uint8_t get_z_index_bits(const css_computed_style *style)
 {
 	uint32_t bits = style->i.bits[Z_INDEX_INDEX];
